<div class="video-wrapper-home">
    <div class="video-home">
        <div class="video-player-home">
            <img alt="Video Player" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) ?>wysiwyg/cms/store/player.png" />
        </div>
        <ul>
	        <li data-video-id="110922383">
                <div class="video-thumb-home">
                    <img alt="Play Video" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) ?>wysiwyg/home/old_man_playlist.jpg" />
                </div>
                <div class="clear"></div>
            </li>
            <li data-video-id="110922505">
                <div class="video-thumb-home">
                    <img alt="Play Video" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) ?>wysiwyg/home/dia_900_playlist.jpg" />
                </div>
                <div class="clear"></div>
            </li>
        </ul>
        <ul>
            <li data-video-id="110922488">
                <div class="video-thumb-home">
                    <img alt="Play Video" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) ?>wysiwyg/home/best_breakfast_drink_playlist.jpg" />
                </div>
                <div class="clear"></div>
            </li>
             <li data-video-id="110922481">
                <div class="video-thumb-home">
                    <img alt="Play Video" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) ?>wysiwyg/home/workout_playlist.jpg" />
                </div>
                <div class="clear"></div>
            </li>
    	</ul>
    		<p>The mission of my BLOG is to illuminate and empower you with so much Natural Healing and Herbal Medicine Wisdom, Specifics, Remedies, Quick Fixes, Programs, Tools and general Know How, that whenever you need it, you've got it.<p>
			<p>Watch hundreds of Dr. Schulze’s Blog videos on health and healing!</p>
			<a class="blink1" href="/blog">WATCH VIDEOS</a></div>
        <div class="clear"></div>
    </div>
</div>