<div class="content-page index-of-ailments">
	<div class="col2 section1">
		<div class="column1">
			<br><img class="commondosage1" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/cms/index-of-ailments/indexail_1.jpg" />
		</div>
		<div class="column2">
			<br><p>A Healthy Lifestyle Comes First! Dr. Schulze always says,“True healing comes from creating a healthy lifestyle, stopping the things you did that made you sick in the first place, and starting new programs of health and wellness, like healthy food programs, elimination programs, detox programs, exercise programs and programs that create emotional wellness. This is true healing!”So work on getting YOU well by adopting these principles, and don’t try to change your life by ONLY using his herbal remedies—change your life by changing YOU! Today, we have discovered the limitations of medical doctors trying to poison people well with chemicals. Let’s be honest—it doesn’t work! Getting well depends how you live your life, and how you change your life when your life depends on it! Being proactive first is what counts!</p>
			
			<p>We must also legally advise you that Dr. Schulze is not a Medical Doctor. His opinions regarding health and healing disease are based on his own personal experience and that of thousands of patients that he treated in his clinic over a period of decades. If you have any illness or disease, we must advise you to consult a licensed medical professional.</p>
		</div>
	</div>
	<div class="col1 section2">
		<div class="column1">
			<h3>HOW TO USE THIS LISTING</h3><br>
			<p>In this listing, we identified different conditions that you might experience. Each is followed by Dr. Schulze’s Herbal Formulas and Programs that he recommends based on his clinical experience. Some conditions have two or more formulas and programs listed. All suggestions are listed in their order of priority, so start with the first formula listed. You may use more than one formula at a time. If you start with one and after a reasonable period of time you do not get the desired results, add the second and then the third recommended formula. Continue to use the first formula when adding the second and so on. Keep in mind that Natural Healing is based on helping your body do the work it was designed to do. So please use Dr. Schulze’s Foundational Products to get the nutrition IN and the toxins OUT, and build a powerful immune system. Then, add specific formulas as you see necessary.</p>
			<p>Read Dr. Schulze’s “20 Steps to a Healthier Life” Book. Call us toll-free at 1-800-HERBDOC (437-2362) and get a FREE copy of this book and/or his “Get Well” CD, which describes each of these 20 steps in more detail. Start all of his Foundational Herbal Formulas and Programs, and you will be well on your way to a healthy and vibrant life!</p>

			<h4>Legal Disclaimer</h4>
			<p class="disclaimer">The following statements have not been evaluated by the Food and Drug Administration. These products are not intended to diagnose, treat, cure or prevent any disease.</p>
		</div>
	</div>
	<div class="section3">
		<div class="page-title">
		<h1>INDEX OF AILMENTS</h1>
		</div>
		<div id="ailments-tabs">
			<div class="tabs-nav-container">
				<ul>
				    <li><a href="#ailments-tabs-1">A - C</a></li>
				    <li><a href="#ailments-tabs-2">D - F</a></li>
				    <li><a href="#ailments-tabs-3">G - I</a></li>
				   	<li><a href="#ailments-tabs-4">J - P</a></li>
				   	<li><a href="#ailments-tabs-5">R - W</a></li>
				</ul>
			</div>
			<div id="ailments-tabs-1">
				<div class="col3">
					<div class="column1">
						<h3>A</h3>
						<ul>
							<li>
								<p><span class="title">Abdominal Bleeding</span></p>
								<p>5-Day BOWEL Detox, Cayenne (Tincture or Powder), HerbalMucil Plus</p>
							</li>

							<li>
								<p><span class="title">Abrasions</a>
								<p>Anti-I Formula, Jojoba & Tea Tree Oil (Ointment or Oil)</span></p>
							</li>

							<li>
								<p><span class="title">Acne</a>
								<p>5-Day BOWEL Detox, 5-Day KIDNEY Detox, 5-Day LIVER Detox, Vegan, Raw Food Program</span></p>
							</li>

							<li>
								<p><span class="title">Adenoids, Inflamed</span></p>
								<p>Daily Oral Therapy, Throat & Tonsil, Cold & Flu Herbal “SHOT”, Echinacea Plus, Children’s Echinacea, SuperTonic, Super-C Plus, Raw Garlic</p>
							</li>

							<li>
								<p><span class="title">AIDS</a>
								<p>Incurables Program</span></p>
							</li>

							<li>
								<p><span class="title">Allergy</a>
								<p>Echinacea Plus, Children’s Echinacea, Lung, Cold & Flu Herbal “SHOT”, 30-Day Detox Program</span></p>
							</li>

							<li>
								<p><span class="title">Alzheimer’s Disease</span></p>
								<p>Brain, SuperFood Plus, Cayenne (Tincture or Powder), Incurables Program, Protect Formula (prevention)</p>
							</li>

							<li>
								<p><span class="title">Anemic</a>
								<p>SuperFood Plus, SuperFood Bar, Super-C Plus, 5-Day LIVER Detox, Organic Fruit and Vegetable Juice</span></p>
							</li>

							<li>
								<p><span class="title">Angina Pectoris</span></p>
								<p>Heart, Cayenne (Tincture or Powder), 30-Day Detox Program</p>
							</li>

							<li>
								<p><span class="title">Animal Bites</span></p>
								<p>Echinacea Plus, Children’s Echinacea, Anti-I Formula </p>
							</li>

							<li>
								<p><span class="title">Antioxidant</span></p>
								<p>SuperFood Plus, Super-C Plus, Protect Formula</p>
							</li>

							<li>
								<p><span class="title">Antiseptic</a>
								<p>Anti-I Formula, Jojoba & Tea Tree Oil (Ointment or Oil), Echinacea Plus, Children’s Ech inacea, Garlic</span></p>
							</li>

							<li>
								<p><span class="title">Anxiety</a>
								<p>Nerve, Brain, SuperFood Plus</span></p>
							</li>

							<li>
								<p><span class="title">Aphrodisiac</span></p>
								<p>Male “SHOT”, Female “SHOT”, Female Formula, Male Formula, Super Ginseng</p>
							</li>

							<li>
								<p><span class="title">Arrhythmia</a>
								<p>Heart, Cayenne (Tincture or Powder), SuperFood Plus, 30-Day Detox Program</span></p>
							</li>

							<li>
								<p><span class="title">Arthritis</a>
								<p>Deep Tissue (Ointment or Oil), Incurables Program</span></p>
							</li>

							<li>
								<p><span class="title">Asthma</a>
								<p>Lung, Incurables Program, Dairy-Free Vegan Food Program</span></p>
							</li>

							<li>
								<p><span class="title">Atherosclerosis	</span></p>
								<p>Heart, Cayenne (Tincture or Powder), Incurables Program, Vegan Food Program</p>
							</li>

							<li>
								<p><span class="title">Athlete’s Foot</span></p>
								<p>Jojoba & Tea Tree Oil (Ointment or Oil), Anti-I Formula, Echinacea Plus</p>
							</li>
						</ul>
					</div>
					<div class="column2">
						<h3>B</h3>
						<ul>
							<li>
								<p><span class="title">Bad Breath</a>
								<p>Daily Oral Therapy, Fresh Breath Plus, Digestive “SHOT”, Digestive Tonic, Tooth & Gum, 5-Day BOWEL Detox</span></p>
							</li>
							<li>
								<p><span class="title">Bladder</a>
								<p>5-Day KIDNEY Detox, K-B Formula, K-B Tea</span></p>
							</li>
							<li>
								<p><span class="title">Bleeding</a>
								<p>Cayenne (Tincture or Powder), Anti-I Formula</span></p>
							</li>
							<li>
								<p><span class="title">Blindness</a>
								<p>Eyebright, Brain, SuperFood Plus, Incurables Program</span></p>
							</li>
							<li>
								<p><span class="title">Blunt Trauma</span></p>
								<p>Ice (immediately), Deep Tissue (Ointment or Oil), Hot & Cold Hydrotherapy</p>
							</li>
							<li>
								<p><span class="title">Boils</a>
								<p>Anti-I Formula, 5-Day BOWEL Detox, 5-Day KIDNEY Detox</span></p>
							</li>
							<li>
								<p><span class="title">Bone, Fractures</span></p>
								<p>Ice (immediately), Deep Tissue (Ointment or Oil), Hot & Cold Hydrotherapy, SuperFood Plus</p>
							</li>
							<li>
								<p><span class="title">Bowel, Inflamed</span></p>
								<p>HerbalMucil Plus, Intestinal Formula #2, 5-Day BOWEL Detox, Nerve</p>
							</li>
							<li>
								<p><span class="title">Brain, Circulation</span></p>
								<p>Brain, Cayenne (Tincture or Powder), SuperFood Plus, Energy “SHOT”, Protect Formula </p>
							</li>
							<li>
								<p><span class="title">Bronchial</a>
								<p>Lung, Air Detox</span></p>
							</li>
							<li>
								<p><span class="title">Bronchitis</a>
								<p>Cold & Flu Herbal “SHOT”, Lung, Echinacea Plus, Children’s Echinacea, SuperTonic, Super-C Plus, Air Detox</span></p>
							</li>
							<li>
								<p><span class="title">Bruises</a>
								<p>Deep Tissue (Ointment or Oil), Hot & Cold Hydrotherapy, SuperFood Plus</span></p>
							</li>
							<li>
								<p><span class="title">Bursitis</a>
								<p>Deep Tissue (Ointment or Oil), Hot & Cold Hydrotherapy</span></p>
							</li>
						</ul>
					</div>
					<div class="column3">
						<h3>C</h3>
						<ul>
							<li>
								<p><span class="title">Cancer</a>
								<p>Incurables Program</span></p>
							</li>
							<li>
								<p><span class="title">Candida Albicans</span></p>
								<p>5-Day BOWEL Detox, Echinacea Plus, Raw Garlic</p>
							</li>
							<li>
								<p><span class="title">Cataracts</a>
								<p>Eyebright, Brain, Cayenne (Tincture or Powder), Incurables Program</span></p>
							</li>
							<li>
								<p><span class="title">Cerebral Hemorrhage</span></p>
								<p>Cayenne (Tincture or Powder), Brain, Heart, Incurables Program</p>
							</li>
							<li>
								<p><span class="title">Cervix Infections</span></p>
								<p>Female Formula, 5-Day KIDNEY Detox, 30-Day Detox Program, Garlic Suppository</p>
							</li>
							<li>
								<p><span class="title">Chest Cold</a>
								<p>Cold & Flu Herbal “SHOT”, Echinacea Plus, Children’s Echinacea, SuperTonic, Super-C Plus, Deep Tissue (Ointment or Oil) on chest</span></p>
							</li>
							<li>
								<p><span class="title">Chicken Pox</span></p>
								<p>Cold & Flu Herbal “SHOT”, Echinacea Plus, Children’s Echinacea, SuperTonic, Jojoba & Tea Tree Oil (Ointment or Oil) on pox</p>
							</li>
							<li>
								<p><span class="title">Childbirth</a>
								<p>SuperFood Plus, Nerve</span></p>
							</li>
							<li>
								<p><span class="title">Cholesterol</span></p>
								<p>Heart, Raw Garlic, 5-Day LIVER Detox, SuperSlim Weight Management System, Vegan Food Program</p>
							</li>
							<li>
								<p><span class="title">Chronic Fatigue</span></p>
								<p>Echinacea Plus, Children’s Echinacea, SuperFood Plus, 30-Day Detox Program</p>
							</li>
							<li>
								<p><span class="title">Circulation, To Enhance</span></p>
								<p>Cayenne (Tincture or Powder), Heart, Brain</p>
							</li>
							<li>
								<p><span class="title">Colds and Flu</span></p>
								<p>Cold & Flu Herbal “SHOT”, Echinacea Plus, Children’s Echinacea, SuperTonic, SuperFood Plus, Super-C Plus, Throat & Tonsil, Lung, Air Detox</p>
							</li>
							<li>
								<p><span class="title">Colic</a>
								<p>Digestive Tonic, Nerve, Digestive “SHOT”</span></p>
							</li>
							<li>
								<p><span class="title">Colitis, Ulcerated</span></p>
								<p>HerbalMucil Plus, Intestinal Formula #2, SuperFood Plus</p>
							</li>
							<li>
								<p><span class="title">Congestive Heart Disease</span></p>
								<p>Heart, Cayenne (Tincture or Powder), Incurables Program, Protect Formula (prevention)</p>
							</li>
							<li>
								<p><span class="title">Conjunctivitis</span></p>
								<p>Eyebright, Chop Onions, Eat Onions</p>
							</li>
							<li>
								<p><span class="title">Constipation</span></p>
								<p>Bowel Flush “SHOT”, Intestinal Formula #1, Intestinal Formula #1 (MAX),  Intestinal Formula #3, 5-Day BOWEL Detox, HerbalMucil Plus (to add fiber)</p>
							</li>
							<li>
								<p><span class="title">Convulsions</span></p>
								<p>Nerve, Digestive “SHOT”, Incurables Program</p>
							</li>
							<li>
								<p><span class="title">Crohn’s Disease</span></p>
								<p>HerbalMucil Plus, Intestinal Formula #2, Nerve, Incurables Program</p>
							</li>
							<li>
								<p><span class="title">Cuts</a>
								<p>Anti-I Formula, Cayenne (Tincture or Powder) to stop bleeding, Echinacea Plus</span></p>
							</li>
							<li>
								<p><span class="title">Cystitis</a>
								<p>5-Day KIDNEY Detox</span></p>
							</li>
						</ul>
					</div>
				</div>
			</div>
			<div id="ailments-tabs-2">
				<div class="col3">
					<div class="column1">
						<h3>D</h3>
						<ul>
							<li>
								<p><span class="title">Depression</a>
								<p>Brain, Nerve, SuperFood Plus, 5-Day BOWEL Detox, Protect Formula (prevention)</span></p>
							</li>
							<li>
								<p><span class="title">Dermatitis</a>
								<p>Jojoba & Tea Tree Oil (Ointment or Oil), 5-Day BOWEL Detox, 5-Day KIDNEY Detox</span></p>
							</li>
							<li>
								<p><span class="title">Detoxification</span></p>
								<p>5-Day BOWEL Detox, 5-Day LIVER Detox, 5-Day KIDNEY Detox, 30-Day Detox Program</p>
							</li>
							<li>
								<p><span class="title">Diabetes</a>
								<p>Incurables Program</span></p>
							</li>
							<li>
								<p><span class="title">Diaper Rash</span></p>
								<p>Jojoba & Tea Tree Oil (Ointment or Oil)</p>
							</li>
							<li>
								<p><span class="title">Diarrhea</a>
								<p>Intestinal Formula #2, HerbalMucil Plus, Echinacea Plus, Children’s Echinacea, 5-Day BOWEL Detox</span></p>
							</li>
							<li>
								<p><span class="title">Diverticulitis/Diverticulosis</span></p>
								<p>5-Day BOWEL Detox, HerbalMucil Plus, Intestinal Formula #2, Incurables Program</p>
							</li>
							<li>
								<p><span class="title">Dizziness</a>
								<p>Brain, Cayenne (Tincture or Powder)</span></p>
							</li>
							<li>
								<p><span class="title">Drug Withdrawal</span></p>
								<p>Nerve, Incurables Program, SuperFood Plus</p>
							</li>
							<li>
								<p><span class="title">Dysentery</span></p>
								<p>Intestinal Formula #2, HerbalMucil Plus, Echinacea Plus, Children’s Echinacea, 5-Day BOWEL Detox</p>
							</li>
						</ul>
					</div>
					<div class="column2">
						<h3>E</h3>
						<ul>
							<li>
								<p><span class="title">Eczema</a>
								<p>Jojoba & Tea Tree Oil (Ointment or Oil), 5-Day BOWEL Detox, 5-Day KIDNEY Detox</span></p>
							</li>
							<li>
								<p><span class="title">Edema</a>
								<p>5-Day KIDNEY Detox, K-B Formula, K-B Tea</span></p>
							</li>
							<li>
								<p><span class="title">Emphysema</a>
								<p>Lung, Air Detox, Incurables Program</span></p>
							</li>
							<li>
								<p><span class="title">Energy, Loss</span></p>
								<p>Energy “SHOT”, SuperFood Plus, Echinacea Plus, Cayenne (Tincture or Powder), 5-Day BOWEL Detox</span></p>
							</li>
							<li>
								<p><span class="title">Epilepsy</a>
								<p>Nerve, Incurables Program</span></p>
							</li>
							<li>
								<p><span class="title">Epstein-Barr Virus</span></p>
								<p>Echinacea Plus, Children’s Echinacea, SuperTonic, 30-Day Detox Program</p>
							</li>
							<li>
								<p><span class="title">Eyes, Injury, Infection</span></p>
								<p>Eyebright, Brain, SuperFood Plus, Chop Onions, Eat Onions</p>
							</li>
							<li>
								<p><span class="title">Eyesight, Loss</span></p>
								<p>Eyebright, Brain, Cayenne (Tincture or Powder), SuperFood Plus, Incurables Program</p>
							</li>
						</ul>
					</div>
					<div class="column3">
						<h3>F</h3>
						<ul>
							<li>
								<p><span class="title">Fainting</a>
								<p>Cayenne (Tincture or Powder), Brain, SuperFood Plus</span></p>
							</li>
							<li>
								<p><span class="title">Fatigue</a>
								<p>Energy “SHOT”, SuperFood Plus, Echinacea Plus, Cayenne (Tincture or Powder), 5-Day BOWEL Detox</span></p>
							</li>
							<li>
								<p><span class="title">Fertility, Men</span></p>
								<p>Male “SHOT”, Male Formula, Super Ginseng, Prostate, 30-Day Detox Program</p>
							</li>
							<li>
								<p><span class="title">Fertility, Women</span></p>
								<p>Female “SHOT”, Female Formula, 30-Day Detox Program</p>
							</li>
							<li>
								<p><span class="title">Fever</a>
								<p>Cold & Flu Herbal “SHOT”, Echinacea Plus, Children’s Echinacea, SuperTonic, Super-C Plus </span></p>
							</li>
							<li>
								<p><span class="title">Fibromyalgia</span></p>
								<p>Incurables Program</p>
							</li>
							<li>
								<p><span class="title">Fits</span></p>
								<p>Nerve, Incurables Program</span></p>
							</li>
							<li>
								<p><span class="title">Food Poisoning</span></p>
								<p>Intestinal Formula #2, Digestive “SHOT”, Digestive Tonic, Echinacea Plus, Children’s Echinacea, Raw Garlic, Bowel Flush “SHOT”</p>
							</li>
							<li>
								<p><span class="title">Frostbite</a>
								<p>Cayenne (Tincture or Powder), Deep Tissue (Ointment or Oil)</span></p>
							</li>
							<li>
								<p><span class="title">Fungus </span></p>
								<p>Jojoba & Tea Tree Oil (Ointment or Oil), Anti-I Formula, Echinacea Plus</p>
							</li>
						</ul>
					</div>
				</div>
			</div>
			<div id="ailments-tabs-3">
				<div class="col3">
					<div class="column1">
						<h3>G</h3>
						<ul>
							<li>
								<p><span class="title">Gallstones</a>
								<p>5-Day LIVER Detox</span></p>
							</li>
							<li>
								<p><span class="title">Gangrene</a>
								<p>Cayenne (Tincture or Powder), Deep Tissue (Ointment or Oil), Incurables Program</span></p>
							</li>
							<li>
								<p><span class="title">Gas</a>
								<p>Digestive “SHOT”, Digestive Tonic, 5-Day BOWEL Detox, 5-Day LIVER Detox</span></p>
							</li>
							<li>
								<p><span class="title">Glands, Swollen</span></p>
								<p>Cold & Flu Herbal “SHOT”, Throat & Tonsil, Echinacea Plus, Children’s Echinacea, SuperTonic, Raw Garlic </p>
							</li>
							<li>
								<p><span class="title">Glaucoma</a>
								<p>Eyebright, Brain, Cayenne (Tincture or Powder), Incurables Program</span></p>
							</li>
							<li>
								<p><span class="title">Gingivitis</a>
								<p>Daily Oral Therapy, Tooth & Gum (in a water pick), Echinacea Plus, Children’s Echinacea</span></p>
							</li>
							<li>
								<p><span class="title">Gout, Pain</a>
								<p>Deep Tissue (Ointment or Oil), 5-Day KIDNEY Detox</span></p>
							</li>
							<li>
								<p><span class="title">Gums, Bleeding</span></p>
								<p>Daily Oral Therapy, Tooth & Gum (in a water pick), Cayenne (Tincture)</p>
							</li>
						</ul>
					</div>
					<div class="column2">
						<h3>H</h3>
						<ul>
							<li>
								<p><span class="title">Hay Fever</a>
								<p>Cold & Flu Herbal “SHOT”, Echinacea Plus, Children’s Echinacea, SuperTonic, Lung</span></p>
							</li>
							<li>
								<p><span class="title">Headache</a>
								<p>Nerve, Brain, 5-Day BOWEL Detox</span></p>
							</li>
							<li>
								<p><span class="title">Heart, Protective</span></p>
								<p>Protect Formula, Heart, Cayenne (Tincture or Powder)</p>
							</li>
							<li>
								<p><span class="title">Heart Attack</span></p>
								<p>Cayenne (Tincture or Powder), Heart</p>
							</li>
							<li>
								<p><span class="title">Heartburn</a>
								<p>Digestive “SHOT”, Digestive Tonic, Intestinal Formulas #1 and #2</span></p>
							</li>
							<li>
								<p><span class="title">Heavy Metal Poisoning</span></p>
								<p>Intestinal Formula #2, 5-Day BOWEL Detox</p>
							</li>
							<li>
								<p><span class="title">Hemoglobin, Low</span></p>
								<p>SuperFood Plus, SuperFood Bar, Use Your Juicer, 30-Day Detox Program</p>
							</li>
							<li>
								<p><span class="title">Hemorrhage</a>
								<p>Cayenne (Tincture or Powder)</span></p>
							</li>
							<li>
								<p><span class="title">Hepatitis</a>
								<p>5-Day LIVER Detox, L-GB Formula</span></p>
							</li>
							<li>
								<p><span class="title">Herpes, Simplex</span></p>
								<p>Anti-I Formula, Raw Garlic</p>
							</li>
							<li>
								<p><span class="title">Herpes, Zoster</span></p>
								<p>Nerve, SuperFood Plus, Anti-I Formula</p>
							</li>
							<li>
								<p><span class="title">Hiatal Hernia</span></p>
								<p>Digestive “SHOT”, Digestive Tonic, Detox Tea, 5-Day LIVER Detox</p>
							</li>
							<li>
								<p><span class="title">Hiccups</a>
								<p>Nerve, Digestive “SHOT”, Digestive Tonic</span></p>
							</li>
							<li>
								<p><span class="title">High Blood Pressure</span></p>
								<p>Heart, Cayenne (Tincture or Powder), Raw Garlic, 5-Day BOWEL Detox</p>
							</li>
							<li>
								<p><span class="title">Hives</a>
								<p>Echinacea Plus, Children’s Echinacea, Nerve, Jojoba & Tea Tree Oil (Ointment or Oil) on hives</span></p>
							</li>
							<li>
								<p><span class="title">Hot Flashes</span></p>
								<p>Female “SHOT”, Female Formula, SuperFood Plus</p>
							</li>
							<li>
								<p><span class="title">Hypertension</span></p>
								<p>Heart, Cayenne (Tincture or Powder), Raw Garlic, 5-Day BOWEL Detox</p>
							</li>
							<li>
								<p><span class="title">Hypoglycemia</span></p>
								<p>SuperFood Bar, SuperFood Plus, 30-Day Detox Program</p>
							</li>
						</ul>
					</div>
					<div class="column3">
						<h3>I</h3>
						<ul>
							<li>
								<p><span class="title">Immune Stimulation</span></p>
								<p>Echinacea Plus, Children’s Echinacea, Cold & Flu Herbal “SHOT”, SuperFood Plus, Super-C Plus</p>
							</li>
							<li>
								<p><span class="title">Impotency</span></p>
								<p>Male “SHOT”, Male Formula, Super Ginseng, Prostate, 30-Day Detox Program</p>
							</li>
							<li>
								<p><span class="title">Incontinence, Men</span></p>
								<p>5-Day KIDNEY Detox, Prostate Formula</p>
							</li>
							<li>
								<p><span class="title">Incontinence, Women</span></p>
								<p>5-Day KIDNEY Detox, Female Plus</p>
							</li>
							<li>
								<p><span class="title">Indigestion</span></p>
								<p>Digestive “SHOT”, Digestive Tonic, Intestinal Formulas #1 and #2</p>
							</li>
							<li>
								<p><span class="title">Infection, External</span></p>
								<p>Anti-I Formula, Jojoba & Tea Tree (Ointment or Oil)</p>
							</li>
							<li>
								<p><span class="title">Infection, Internal</span></p>
								<p>Cold & Flu Herbal “SHOT”, Echinacea Plus, Children’s Echinacea, SuperTonic, Raw Garlic</p>
							</li>
							<li>
								<p><span class="title">Infertility</span></p>
								<p>Female “SHOT”, Female Formula, 30-Day Detox Program</p>
							</li>
							<li>
								<p><span class="title">Influenza</span></p>
								<p>Cold & Flu Herbal “SHOT”, Echinacea Plus, Children’s Echinacea, SuperTonic, SuperFood Plus, Super-C Plus, Throat & Tonsil, Lung, Air Detox</p>
								</li>
							<li>
								<p><span class="title">Insect Bites</span></p>
								<p>Echinacea Plus, Children’s Echinacea, Anti-I Formula, Bug Barrier, Deep Tissue (Ointment or Oil) for itch</p>
							</li>
							<li>
								<p><span class="title">Insomnia</a>
								<p>Nerve</span></p>
							</li>
							<li>
								<p><span class="title">Irritable Bowel</span></p>
								<p>HerbalMucil Plus, Intestinal Formula #2, Nerve, 5-Day BOWEL Detox, 30-Day Detox Program</p>
							</li>
							<li>
								<p><span class="title">Itching</a>
								<p>Deep Tissue (Ointment or Oil), Jojoba & Tea Tree (Ointment or Oil), Echinacea Plus, Children’s Echinacea</span></p>
							</li>
						<ul>
					</div>
				</div>
			</div>
			<div id="ailments-tabs-4">
				<div class="col3">
					<div class="column1">
					<h3>J</h3>
					<ul>
						<li>
							<p><span class="title">JaundicE</a>
							<p>5-Day LIVER Detox, L-GB Formulae</span></p>
						</li>
						<h3>K</h3>
						<li>
							<p><span class="title">Kidney Infection</span></p>
							<p>5-Day KIDNEY Detox, K-B Formula, K-B Tea</p>
						</li>
						<li>
							<p><span class="title">Kidney Stones</span></p>
							<p>5-Day KIDNEY Detox, Dr. Schulze’s Dissolve Routine</p>
						</li>
						<h3>L</h3>
						<li>
							<p><span class="title">Laryngitis</a>
							<p>Throat & Tonsil, Cold & Flu Herbal “SHOT”, Echinacea Plus, Children’s Echinacea, SuperTonic</span></p>
						</li>
						<li>
							<p><span class="title">Leg Ulcers</a>
							<p>5-Day BOWEL Detox, Echinacea Plus</span></p>
						</li>
						<li>
							<p><span class="title">Ligament, Sprains</span></p>
							<p>Deep Tissue (Ointment or Oil), SuperFood Plus, Hot & Cold Hydrotherapy</p>
						</li>
						<li>
							<p><span class="title">Liver, All Problems</span></p>
							<p>5-Day LIVER Detox</p>
						</li>
						<li>
							<p><span class="title">Low Energy</span></p>
							<p>Energy “SHOT”, SuperFood Plus, Echinacea Plus, Cayenne (Tincture or Powder), 5-Day BOWEL Detox</span></p>
							
						</li>
						<li>
							<p><span class="title">Lumbago</a>
							<p>Deep Tissue (Ointment or Oil), Hot & Cold Hydrotherapy</span></p>
						</li>
						<li>
							<p><span class="title">Lung, Congestion or Infection</span></p>
							<p>Lung, Cold & Flu Herbal “SHOT”, Echinacea Plus, Children’s Echinacea, SuperTonic, Air Detox</p>
						</li>
						<li>
							<p><span class="title">Lupus</a>
							<p>Echinacea Plus, Children’s Echinacea, Incurables Program</span></p>
						</li>
					</ul>
					</div>
					<div class="column2">
						<h3>M</h3>
						<ul>
							<li>
								<p><span class="title">Malaria</a>
								<p>Cold & Flu Herbal “SHOT”, Echinacea Plus, Children’s Echinacea, Incurables Program</span></p>
							</li>
							<li>
								<p><span class="title">Malnutrition</span></p>
								<p>SuperFood Plus, SuperFood Bar, 5-Day BOWEL Detox</p>
							</li>
							<li>
								<p><span class="title">Mastitis</a>
								<p>Echinacea Plus, Deep Tissue (Ointment or Oil), Hot & Cold Hydrotherapy</span></p>
							</li>
							<li>
								<p><span class="title">Measles</a>
								<p>Cold & Flu Herbal “SHOT”, Echinacea Plus, Children’s Echinacea, SuperFood Plus, SuperTonic</span></p>
							</li>
							<li>
								<p><span class="title">Memory</a>
								<p>Brain, Energy “SHOT”, SuperFood Plus, Cayenne (Tincture or Powder), 5-Day BOWEL Detox, Protect Formula (prevention) </span></p>
							</li>
							<li>
								<p><span class="title">Meningitis</a>
								<p>Cold & Flu Herbal “SHOT”, Echinacea Plus, Children’s Echinacea, Brain, Raw Garlic, Incurables Program</span></p>
							</li>
							<li>
								<p><span class="title">Menopause</a>
								<p>Female “SHOT”, Female Formula, SuperFood Plus</span></p>
							</li>
							<li>
								<p><span class="title">Menstrual Cramps</span></p>
								<p>Female “SHOT”, Female Formula, Nerve, 5-Day BOWEL Detox</p>
							</li>
							<li>
								<p><span class="title">Menstruation, Irregular</span></p>
								<p>Female “SHOT”, Female Formula</p>
							</li>
							<li>
								<p><span class="title">Mental Fatigue</span></p>
								<p>Energy “SHOT”, Brain, SuperFood Plus, Cayenne (Tincture or Powder)</p>
							</li>
							<li>
								<p><span class="title">Mercury Poisoning</span></p>
								<p>Intestinal Formula #2, 5-Day BOWEL Detox</p>
							</li>
							<li>
								<p><span class="title">Migraine</a>
								<p>Nerve, Brain, Cayenne (Tincture or Powder), 5-Day BOWEL Detox</span></p>
							</li>
							<li>
								<p><span class="title">Mumps</a>
								<p>Cold & Flu Herbal “SHOT”, Echinacea Plus, Children’s Echinacea, SuperTonic, SuperFood Plus</span></p>
							</li>
							<li>
								<p><span class="title">Muscle, Cramps, Spasms</span></p>
								<p>Nerve, SuperFood Plus, Deep Tissue (Ointment or Oil)</p>
							</li>
							<li>
								<p><span class="title">Muscle, Sore, Torn, Sprains</span></p>
								<p>Deep Tissue (Ointment or Oil), Nerve, Hot & Cold Hydrotherapy</p>
							</li>
						</ul>
					</div>
					<div class="column3">
						<h3>N</h3>
						<ul>
							<li>
								<p><span class="title">Nerve Repair, Damage</span></p>
								<p>Nerve, Deep Tissue (Ointment or Oil), SuperFood Plus</p>
							</li>
							<li>
								<p><span class="title">Night Sweats</span></p>
								<p>Female “SHOT”, Female Formula, SuperFood Plus</p>
							 </li>
							<li>
								<p><span class="title">Nursing Moms</span></p>
								<p>SuperFood Plus, SuperFood Bar, Super-C Plus</p>
							</li>
						</ul>
						<h3>P</h3>
						<ul>
							<li>
								<p><span class="title">Pain</a>
								<p>Nerve, Deep Tissue (Ointment or Oil)</span></p>
							</li>
							<li>
								<p><span class="title">Palpitations</span></p>
								<p>Heart, Cayenne (Tincture or Powder), Nerve</p>
							</li>
							<li>
								<p><span class="title">Pap Smear, Abnormal</span></p>
								<p>Female Formula, Garlic Suppository, 5-Day BOWEL Detox</p>
							</li>
							<li>
								<p><span class="title">Parasites, General</span></p>
								<p>Parasites, General</p>
							</li>
							<li>
								<p><span class="title">Parasites, Intestinal</span></p>
								<p>Bowel Flush “SHOT”, 5-Day BOWEL Detox, 5-Day LIVER Detox</p>
							</li>
							<li>
								<p><span class="title">Parkinson’s Disease</span></p>
								<p>Nerve, Brain, Incurables Program</p>
							</li>
							<li>
								<p><span class="title">Pink Eye</span></p>
								<p>Eyebright, Chop Onions, Eat Onions</p>
							</li>
							<li>
								<p><span class="title">PMS</a>
								<p>Female “SHOT”, Female Plus, SuperFood Plus, Nerve, K-B Formula, K-B Tea</span></p>
							</li>
							<li>
								<p><span class="title">Pneumonia</a>
								<p>Cold & Flu Herbal “SHOT”, Echinacea Plus, Children’s Echinacea, Lung, SuperTonic, Garlic, Air Detox</span></p>
							</li>
							<li>
								<p><span class="title">Poison Ivy</a>
								<p>Echinacea Plus, Children’s Echinacea, Anti-I Formula, Jojoba & Tea Tree Oil (Ointment or Oil), Deep Tissue (Ointment or Oil) for </p>itching</p>
							</li>
							<li>
								<p><span class="title">Poison Oak</span></p>
								<p>Echinacea Plus, Children’s Echinacea, Anti-I Formula, Jojoba & Tea Tree Oil (Ointment or Oil), Deep Tissue (Ointment or Oil) for itching</p>
							</li>
							<li>
								<p><span class="title">Prostate, Enlarged, Infected</span></p>
								<p>Prostate Formula, Male Formula, 5-Day BOWEL Detox, 5-Day KIDNEY Detox</p>
							</li>
							<li>
								<p><span class="title">Psoriasis</a>
								<p>Jojoba & Tea Tree Oil (Ointment or Oil), 30-Day Detox Program</span></p>
							</li>
						</ul>
					</div>
				</div>
			</div>
			<div id="ailments-tabs-5">
				<div class="col3">
					<div class="column1">
						<h3>R</h3>
						<ul>
							<li>
								<p><span class="title">Radiation Poisoning</span></p>
								<p>Intestinal Formula #2, SuperFood Plus, Incurables Program</p>
							</li>
							<li>
								<p><span class="title">Ringworm</a>
								<p>Echinacea Plus, Children’s Echinacea, Detox Formula, Jojoba & Tea Tree Oil (Ointment or Oil), Raw Garlic</span></p>
							</li>
						</ul>
						<h3>S</h3>
						<ul>
							<li>
								<p><span class="title">Sciatica</a>
								<p>Deep Tissue (Ointment or Oil), Nerve, Hot & Cold Hydrotherapy, Intestinal Formula #1</span></p>
							</li>
							<li>
								<p><span class="title">Seizures </span></p>
								<p>Nerve, Incurables Program</p>
							</li>
							<li>
								<p><span class="title">Sexual Desire, Female</span></p>
								<p>Female “SHOT”, Female Formula, SuperFood Plus</p>
							</li>
							<li>
								<p><span class="title">Sexual Desire, Male</span></p>
								<p>Male “SHOT”, Male Formula, Super Ginseng, SuperFood Plus</p>
							</li>
							<li>
								<p><span class="title">Shingles</span></p>
								<p>Nerve, SuperFood Plus, Anti-I Formula</p>
							</li>
							<li>
								<p><span class="title">Sinus Congestion</span></p>
								<p>Cold & Flu Herbal “SHOT”, Echinacea Plus, Children’s Echinacea, Lung, SuperTonic, Air Detox</p>
							</li>
							<li>
								<p><span class="title">Sinus Infection</span></p>
								<p>Cold & Flu Herbal “SHOT”, Echinacea Plus, Children’s Echinacea, SuperTonic, Cold & Flu Program, Air Detox</p>
							</li>
							<li>
								<p><span class="title">Skin, Dry, Chapped, Sore</span></p>
								<p>Jojoba & Tea Tree Oil (Ointment or Oil), SuperFood Plus</p>
							</li>
							<li>
								<span class="title">Skin, Elimination</span></li>
								<p>5-Day BOWEL Detox, 5-Day KIDNEY Detox, 5-Day LIVER Detox, Vegan, Raw Food Program</span></p>
							</li>
							<li>
								<p><span class="title">Smoking, To Stop</span></p>
								<p>Nerve, Lung, SuperFood Plus</p>
							</li>
							<li>
								<p><span class="title">Sprains</span></p>
								<p>Deep Tissue (Ointment or Oil), Nerve, Hot & Cold Hydrotherapy</p> 
							</li>
							<li>
								<p><span class="title">Stings</span></p>
								<p>Echinacea Plus, Children’s Echinacea, Anti-I Formula, Bug Barrier, Deep Tissue (Ointment or Oil) for itch</p>
							</li>
							<li>
								<p><span class="title">Stomach Cramps</span></p>
								<p>Digestive “SHOT”, Digestive Tonic, Nerve</p>
							</li>
							<li>
								<p><span class="title">Stomach Ulcers</span></p>
								<p>Digestive “SHOT”, HerbalMucil Plus, Intestinal Formula #2, 5-Day BOWEL Detox</p>
							</li>
							<li>
								<p><span class="title">Stress</span></p>
								<p>Nerve, Brain, SuperFood Plus</p>
							</li>
							<li>
								<p><span class="title">Stroke</span></p>
								<p>Cayenne (Tincture or Powder), Brain, Heart, Incurables Program</p>
							</li>
							<li>
								p><span class="title">Sty </span></li>
								<p>Eyebright, Brain, SuperFood Plus, Chop Onions, Eat Onions</p>
							</li>
						</ul>
					</div>
					<div class="column2">
						<h3>T</h3>
						<ul>
							<li>
								<p><span class="title">Tachycardia</span></p>
								<p>Heart, Cayenne (Tincture or Powder), 5-Day BOWEL Detox, Incurables Program</p>
							</li>
							<li>
								<p><span class="title">Teething</a>
								<p>Nerve, Tooth & Gum, Echinacea Plus (topical)</span></p>
							</li>
							<li>
								<p><span class="title">Tendon, Sprains </span></p>
								<p>Deep Tissue (Ointment or Oil), Nerve, Hot & Cold Hydrotherapy</p>
							</li>
							<li>
								<p><span class="title">Throat, Sore</span></p>
								<p>Daily Oral Therapy, Throat & Tonsil, Cold & Flu Herbal “SHOT”, Echinacea Plus, Children’s Echinacea, SuperTonic</p>
							</li>
							<li>
								<p><span class="title">Tinnitus</a>
								<p>Brain, Cayenne (Tincture or Powder), Nerve, SuperFood Plus</span></p>
							</li>
							<li>
								<p><span class="title">Tonsillitis</span></p>
								<p>Daily Oral Therapy, Cold & Flu Herbal “SHOT”, Throat & Tonsil, Echinacea Plus, Children’s Echinacea, SuperTonic, Raw Garlic, Air Detox</p>
							</li>
							<li>
								<p><span class="title">Toothache</a>
								<p>Daily Oral Therapy, Tooth & Gum, Nerve, Echinacea Plus</span></p>
							</li>
							<li>
								<p><span class="title">Tooth, Bone Loss</span></p>
								<p>Daily Oral Therapy, Tooth & Gum (in a water pick), SuperFood Plus</p>
							</li>
							<li>
								<p><span class="title">Tooth Infection</span></p>
								<p>Daily Oral Therapy, Tooth & Gum (in a water pick), Anti-I Formula, Echinacea Plus, Children’s Echinacea, Raw Garlic</p>
							</li>
							<li>
								<p><span class="title">Tremors</a>
								<p>Nerve, SuperFood Plus</span></p>
							</li>
							<li>
								<p><span class="title">Tumors</span></p>
								<p>Incurables Program</span></p>
							</li>
						</ul>
					</div>
					<div class="column3">
						<h3>V</h3>
						<ul>
							<li>
								<p><span class="title">Vaginal Dryness</span></p>
								<p>Female “SHOT”, Female Formula</p>
							</li>
							<li>
								<p><span class="title">Vaginal Infection</span></p>
								<p>Echinacea Plus, 5-Day KIDNEY Detox, Garlic Suppository</p>
							</li>
							<li>
								<p><span class="title">Virus</a>
								<p>Cold & Flu Herbal “SHOT”, Echinacea Plus, Children’s Echinacea, SuperTonic, Super-C Plus, Raw Garlic</span></p>
							</li>
							<li>
								<p><span class="title">Vomiting</a>
								<p>Digestive “SHOT”, Digestive Tonic</span></p>
							</li>
							<li>Digestive “SHOT”, Digestive Tonic</li>
						</ul>
						<h3>W</h3>
						<ul>
							<li>
								<p><span class="title">Warts</a>
								<p>Anti-I Formula, Echinacea Plus (used both internally and externally), Raw Garlic</span></p>
							</li>
							<li>
								<p><span class="title">Water Retention</span></p>
								<p>5-Day KIDNEY Detox, Female Plus, Female “SHOT”</p>
							</li>
							<li>
								<p><span class="title">Weight Management</span></p>
								<p>SuperSlim Weight Management System</p>
							</li>
							<li>
								<p><span class="title">Wheezing</a>
								<p>Lung, SuperTonic, Air Detox</span></p>
							</li>
							<li>
								<p><span class="title">Wounds, Cleansing</span></p>
								<p>Anti-I Formula</p>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>