<?php
/* Author: Aydus
 * Description: Mage_Tax_Block_Checkout_Shipping
 *  - Progress review shipping total title
 */
?>
<?php if ($this->displayBoth()):?>
<tr>
    <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
    <?php if (Mage::registry('reviewProgressTotals')): ?>
    	<?php echo $this->__('Shipping') ?>
    <?php else: ?>
    	<?php echo $this->getExcludeTaxLabel() ?>
    <?php endif;?>
    </td>
    <td style="<?php echo $this->getStyle() ?>" class="a-right">
        <?php echo $this->helper('checkout')->formatPrice($this->getShippingExcludeTax()) ?>
    </td>
</tr>
<tr>
    <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
    <?php if (Mage::registry('reviewProgressTotals')): ?>
    	<?php echo $this->__('Shipping') ?>
    <?php else: ?>
    	<?php echo $this->getIncludeTaxLabel() ?>
    <?php endif;?>
    </td>
    <td style="<?php echo $this->getStyle() ?>" class="a-right">
        <?php echo $this->helper('checkout')->formatPrice($this->getShippingIncludeTax()) ?>
    </td>
</tr>
<?php elseif($this->displayIncludeTax()) : ?>
<tr>
    <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
    <?php if (Mage::registry('reviewProgressTotals')): ?>
    	<?php echo $this->__('Shipping') ?>
    <?php else: ?>
	    <?php echo $this->getTotal()->getTitle() ?>
    <?php endif;?>
    </td>
    <td style="<?php echo $this->getStyle() ?>" class="a-right">
        <?php echo $this->helper('checkout')->formatPrice($this->getShippingIncludeTax()) ?>
    </td>
</tr>
<?php else:?>
<tr>
    <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
    <?php if (Mage::registry('reviewProgressTotals')): ?>
    	<?php echo $this->__('Shipping') ?>
    <?php else: ?>
        <?php echo $this->escapeHtml($this->getTotal()->getTitle()) ?>
    <?php endif;?>
    </td>
    <td style="<?php echo $this->getStyle() ?>" class="a-right">
        <?php echo $this->helper('checkout')->formatPrice($this->getShippingExcludeTax()) ?>
    </td>
</tr>
<?php endif;?>
