<h1>Job Description</h1>
<div class="table-container">
    <div class="column-left-container">
        <div class="column left">
            <div class="inner-tube">
                <div class="summary">
                    <p>Job Title: <span>Call Center Agent</span></p>
                    <p>Location: <span>Marina Del Rey</span></p>
                    <p>State: <span>California</span></p>
                    <p>Job Type: <span>Full Time Employee</span></p>
                    <p>Job Description:</p>
                </div>
                <div class="description">
					<p>Dr Schulze's Botanical Pharmacy, distributor of effective, high quality herbal products and programs is looking for a Customer Care Representative for our Call Center located in Marina Del Rey, CA. This Person will be responsible for taking inbound calls from our customers, educating and guiding them on selections of our products and programs</p>
					<h2>Primary Responsibilities</h2>
                    	<ul>
                    		<li>
                    			 Answer inbound calls and respond to customer orders and requests.
                    		</li>
                    		<li>
                    			Follow-up on customer inquiries not immediately resolved.
                    		</li>
                    		<li>
                    			Complete call logs and implement changes to customer accounts if needed.
                    		</li>
                    		<li>
                    			Must be punctual, reliable, flexible with scheduling, and have attention to detail.
                    		</li>
                    	</ul>
                    <h2>Qualifications</h2>
                    <h2>Experience</h2>
                    <ul>
                    	<li>Minimum 12 months Call Center experience.</li>
						<li>Proficient Computer skills in Excel and MS Word</li>
						<li>Type minimum of 40 words per minute</li>
                    </ul>
                    
                    <h2>Skills</h2>
                    <ul>
	                    <li>Display a helpful and courteous attitude when interacting with internal customers.</li>
						<li>Strong oral communication.</li>
						<li>Ability to actively listen and communicate effectively with new and existing customers on the phone.</li>
                    </ul>
                    <h2>Work hours</h2>
                    <h2>Call Center hours are 6:00am--7:00pm Monday through Saturday; Sunday 7:00am-3:30pm. Schedules are determined by management & vary based on scheduling needs.</h2>
                    <h2>Looking for full time and part time employees.</h2>
                    
                     <a class="blink1" href="http://americanbotanicalpharmacy.theresumator.com/apply/NZtHZ3/Call-Center-Representative.html">CLICK HERE TO APPLY FOR JOB</a>
                    
                 </div>
            </div>
        </div>
    </div>

    <div class="column right">
        <div class="inner-tube">
            <h4>A few handy tips.</h4>
            <h5>An accurate resume is key.</h5>
            <p>The resume stored in your profile is viewable by recruiters and hiring managers for each position to which you apply. Be sure it realistically represents your skills, knowledge, and experience.</p>
            <h5>What to expect.</h5>
            <p>You'll receive an automated confirmation each time your resume is successfully submitted for an open position. If a recruiter or hiring manager wants to discuss next steps, they'll get in touch using the contact information from your profile or resume.</p>
            <p>You don't necessarily have to be an expert. The best way to understand our company and our customers is to use our products. And if you have passion for what we do and why we do it, even better. But if you have attention to detail, a collaborative spirit, and a readiness to learn, don't worry, we'll help you make the switch once you arrive.</p>
        </div>
    </div>
</div>