<h1>Job Description</h1>
<div class="table-container">
    <div class="column-left-container">
        <div class="column left">
            <div class="inner-tube">
                <div class="summary">
                    <p>Job Title: <span>Call Center Manager</span></p>
                    <p>Location: <span>Marina Del Rey</span></p>
                    <p>State: <span>California</span></p>
                    <p>Job Type: <span>Full Time Employee</span></p>
                    <p>Job Description:</p>
                </div>
                <div class="description">
                    
                    <h2>About Us</h2>
					<p>Dr. Schulze’s American Botanical Pharmacy is a growth-oriented distributor of quality herbal products. Our people love challenges, take ownership and thrive in a fast-paced environment. Most important, we are passionate about creating powerful health for all and a culture of customer service excellence. If you find our philosophy to be a perfect match, please apply for our Contact Center Manager position with competitive compensation and growth potential. This position will be based in our beautiful headquarters in fresh and breezy Marina Del Rey. </p>
                    <h2>SUMMARY</h2>
                    <p>This position is ideal for a leader who manages and directs all aspects of the customer contact center operation while fostering a consistent culture of customer service excellence and collaboration. This leader is accountable for implementing and reviewing all Contact Center policies, KPIs and business objectives. The Contact Center Manager is a role model of customer service excellence for his/her direct reports and motivates the entire team to achieve company customer service standards and revenue goals. </p>
                    <h2>REQUIRED BACKGROUND AND QUALIFICATIONS</h2>
                    	<ul>
                    		<li>
                    			Bachelor’s degree from an accredited university and/or equivalent experience required
                    		</li>
                    		<li>
                    			3+ years of managerial experience in a high-volume call center experience required
                    		</li>
                    		<li>
                    			3+ years of proven operational results in a high-volume call center required
                    		</li>
                    		<li>
                    			Must have ability to communicate articulately, motivate and lead teams effectively 
                    		</li>
                    		<li>
                    			Proven ability to perform personnel management activities including recruiting, hiring, evaluating performance, salary management and talent development 
                    		</li>
                    		<li>
                    			Proven ability to align teams to drive sales and to achieve KPIs for assigned unit
                    		</li>
                    		<li>
                    			Proven ability to manage ambiguity and change in a positively influential manner
                    		</li>
                    		<li>
                    			Proven ability to synthesize first-hand customer information and use it to increase sales and to elevate customer service excellence 
                    		</li>
                    		<li>
                    			Interpret statistical data and complex budget data to drive Contact Center team efficiency
                    		</li>
                    		<li>
                    			Collaborate with IT, Marketing, Retail, Merchandising and Shipping to implement new programs, drive continual process improvements with service excellence in mind
                    		</li>
                    		<li>
                    			Must have computer literacy and proficiency in full Microsoft Office suite
                    		</li>
                    		<li>
                    			Ability to work some weekends and holidays depending on business and customer needs
                    		</li>
                    		<li>
                    			Experience with CommercialWare, MICROS, or Datavantage software a major plus
                    		</li>
                    		<li>
                    			ICMI professional certification, or Call Center Management certification preferred 
                    		</li>
                    	</ul>
                    
                     <a class="blink1" href=" http://americanbotanicalpharmacy.theresumator.com/apply/J6E5XE/Call-Center-Manager.html">CLICK HERE TO APPLY FOR JOB</a>
                    
                 </div>
            </div>
        </div>
    </div>

    <div class="column right">
        <div class="inner-tube">
            <h4>A few handy tips.</h4>
            <h5>An accurate resume is key.</h5>
            <p>The resume stored in your profile is viewable by recruiters and hiring managers for each position to which you apply. Be sure it realistically represents your skills, knowledge, and experience.</p>
            <h5>What to expect.</h5>
            <p>You'll receive an automated confirmation each time your resume is successfully submitted for an open position. If a recruiter or hiring manager wants to discuss next steps, they'll get in touch using the contact information from your profile or resume.</p>
            <p>You don't necessarily have to be an expert. The best way to understand our company and our customers is to use our products. And if you have passion for what we do and why we do it, even better. But if you have attention to detail, a collaborative spirit, and a readiness to learn, don't worry, we'll help you make the switch once you arrive.</p>
        </div>
    </div>
</div>