<h1>Job Description</h1>
<div class="table-container">
    <div class="column-left-container">
        <div class="column left">
            <div class="inner-tube">
                <div class="summary">
                    <p>Job Title: <span>Manager, Warehouse</span></p>
                    <p>Location: <span>Marina Del Rey</span></p>
                    <p>State: <span>California</span></p>
                    <p>Job Type: <span>Full Time Employee</span></p>
                    <p>Job Description:</p>
                </div>
                <div class="description">
                    <h2>About Us:</h2>
					<p>Dr. Schulze's American Botanical Pharmacy (ABP), located in Marina del Rey, CA is a privately held business that specializes in the development, manufacture, and distribution of Dr. Schulze's original herbal formula and programs worldwide. The key to our success is a culture that continually strives for excellence in quality and in the customer experience.</p>
                    <h2>SUMMARY</h2>
                    <p>The role of Warehouse Manager at ABP requires an individual who can supervise employees while minimalizing problems in warehouse and logistics management. We are looking for an experienced leader with excellent people management skills and practices who can connect with our staff while streamlining processes and enhancing productivity.</p>
                    <h2>JOB DESCRIPTION:</h2>
                    <p>The Warehouse Manager role will direct and coordinate all shipping, receiving and inventory. This role drives operational excellence by ensuring that all orders are shipping on time, the warehouse is organized and clean, inventory is accurate and employees are properly trained on safety and other job requirements. The warehouse business hours are from 8:00am - 5:00 pm Monday through Friday.</p>
                    <h2>RESPONSIBILITIES:</h2>
                    	<ul>
                    		<li>
                    			Must be able to deal with general management and strategic planning while also able to involve the team in practical and productive work on the warehouse floor
                    		</li>
                    		<li>
                    			Ensure that employees are regularly briefed, supervised and trained and that all machinery or vehicles are maintained upholding health, safety and security in the work place at all times
                    		</li>
                    		<li>
                    			Must have ability to ensure employees's safety and compliance with OSHA and other applicable rules
                    		</li>
                    		<li>
                    			Manage regular stock of the inventory, keeping systems up to date by producing regular reports and planning for future capacity requirements
                    		</li>
                    		<li>
                    			Maintain budgets and environmental standards, fulfilling any obligations given by the executive office 
                    		</li>
                    		<li>
                    			Manage and communicate with distributors, suppliers, employees and head office to ensure quality and delivery standards are upheld
                    		</li>
						</ul>
					<h2>EXPERIENCE REQUIRED:</h2>
                    	<ul>
                    		<li>
                    			5 - 7 years of experience in inventory, distribution and warehouse management
                    		</li>
                    		<li>Solid organizational skills are required as the Warehouse Manager centers on the organization of people, stock and budgets while planning for the future</li>
                    		<li>Ability to lead and motivate a workforce and encourage strong teamwork</li>
                    		<li>Proficiency in Microsoft Office and other enterprise software and inventory applications</li>
                    	</ul>
                    <h2>EDUCATIONAL REQUIRED:</h2>
                    	<ul>
                    		<li>
                    			BA/BS Degree Preferred
                    		</li>
                    		<li>
                    			Relevant certification in supply chain and business management
                    		</li>
                    		<li>
                    			Minimum 3 years of warehouse management experience with strong, recent professional references
                    		</li>                    		
                    	</ul>
                    <h2>CANDIDATE SUBMISSIONS:</h2>
                   	<h2>Please submit resume with cover letter directly to Recruit@herbdoc.com</h2>

                    <a class="blink1 read-more" href="http://americanbotanicalpharmacy.theresumator.com/apply/1fPfDZ/Warehouse-Manager.html">CLICK HERE TO APPLY FOR JOB</a>
                    
                    
                 </div>
            </div>
        </div>
    </div>

    <div class="column right">
        <div class="inner-tube">
            <h4>A few handy tips.</h4>
            <h5>An accurate resume is key.</h5>
            <p>The resume stored in your profile is viewable by recruiters and hiring managers for each position to which you apply. Be sure it realistically represents your skills, knowledge, and experience.</p>
            <h5>What to expect.</h5>
            <p>You'll receive an automated confirmation each time your resume is successfully submitted for an open position. If a recruiter or hiring manager wants to discuss next steps, they'll get in touch using the contact information from your profile or resume.</p>
            <p>You don't necessarily have to be an expert. The best way to understand our company and our customers is to use our products. And if you have passion for what we do and why we do it, even better. But if you have attention to detail, a collaborative spirit, and a readiness to learn, don't worry, we'll help you make the switch once you arrive.</p>
        </div>
    </div>
</div>