<h1>Job Description</h1>
<div class="table-container">
    <div class="column-left-container">
        <div class="column left">
            <div class="inner-tube">
                <div class="summary">
                    <p>Job Title: <span>Manager, Retail Store</span></p>
                    <p>Location: <span>Marina Del Rey</span></p>
                    <p>State: <span>California</span></p>
                    <p>Job Type: <span>Full Time Employee</span></p>
                    <p>Job Description:</p>
                </div>
                <div class="description">
                    <h2>About Us:</h2>
					<p>Dr. Schulze’s American Botanical Pharmacy (ABP), located in Marina del Rey, CA is a privately held business that specializes in the development, manufacture, and distribution of Dr. Schulze’s original herbal formula and programs worldwide. The key to our success is a culture that continually strives for excellence in quality and in the customer experience.</p>
                    <h2>SUMMARY</h2>
                    <p>The role of Manager, Retail Store at ABP requires an experienced Retail Manager/Leader with a strong ability to connect with our customers and staff while streamlining processes for efficiency. We are looking for a caring individual to instill and maintain the Tiffany’s, Zappos and Mercedes retail brand approach focused on service excellence.</p>
                    <h2>JOB DESCRIPTION:</h2>
                    <p>The Retail Store Manager role covers all aspects of retail management at ABP including: scheduling, staff management, recruitment, planning and performance Management, sales tracking and training and development. The selected candidate is responsible for the day to day running of the store, customer experience, sales, brand protection, and personnel management for a staff of 10-15 employees. Success in the role requires an individual whose demeanor exudes a sense of competence, clarity, and leadership. The Retail Store Manager reports to the COO. Salary range is $65-75k annually, plus performance bonus.</p>
                    <h2>RESPONSIBILITIES:</h2>
                    	<ul>
                    		<li>
                    			Effectively manage the growth of the retail store while always improving the customer experience
                    		</li>
                    		<li>
                    			Quality staff acquisition and retention
                    		</li>
                    		<li>
                    			Maintain store inventory systems
                    		</li>
                    		<li>
                    			Maintain attractive and clean product displays and store presentation
                    		</li>
                    		<li>
                    			Engage customers in Dr. Schulze’s message, products and programs 
                    		</li>
                    		<li>
                    			Build an overall effective team to maintain a culture of service excellence in the retail store
                    		</li>
						</ul>
					<h2>EXPERIENCE REQUIRED:</h2>
                    	<ul>
                    		<li>
                    			Exceptional organizational, attention to details and follow-through skills
                    		</li>
                    		<li>Strong decision-making skills, including ability to make on-demand judgment calls, utilizing staff and internal / external resources</li>
                    		<li>Proven ability to manage conflict</li>
                    		<li>Excellent verbal communication skills</li>
                    		<li>Ability to interact with all personality types and behaviors; flexibility</li>
                    		<li>Ability to work calmly and effectively in a high-pressure, fast-paced environment</li>
                    		<li>Ability to deal with multiple projects and tight deadlines</li>
                    		<li>Ability to maintain confidentiality and trust with employees</li>
                    		<li>Proficient in Office Software Suite (Word, Excel, PowerPoint, etc.</li>
                    	</ul>
                    <h2>EDUCATIONAL REQUIRED:</h2>
                    	<ul>
                    		<li>
                    			Minimum 3 years retail management experience with strong, recent professional references BA/BS Degree Preferred
                    		</li>
                    	</ul>
                    <h2>CANDIDATE SUBMISSIONS:</h2>
                    	<ul>
                    		<li>
                    			Exceptional organizational, attention to details and follow-through skills
                    		</li>
                    	</ul>

                    	<h2>Please submit resume with cover letter directly to Recruit@herbdoc.com</h2>

                    <a class="blink1 read-more" href="http://americanbotanicalpharmacy.theresumator.com/apply/BElCYN/Manager-Retail-Store.html">CLICK HERE TO APPLY FOR JOB</a>
                    
                    
                 </div>
            </div>
        </div>
    </div>

    <div class="column right">
        <div class="inner-tube">
            <h4>A few handy tips.</h4>
            <h5>An accurate resume is key.</h5>
            <p>The resume stored in your profile is viewable by recruiters and hiring managers for each position to which you apply. Be sure it realistically represents your skills, knowledge, and experience.</p>
            <h5>What to expect.</h5>
            <p>You'll receive an automated confirmation each time your resume is successfully submitted for an open position. If a recruiter or hiring manager wants to discuss next steps, they'll get in touch using the contact information from your profile or resume.</p>
            <p>You don't necessarily have to be an expert. The best way to understand our company and our customers is to use our products. And if you have passion for what we do and why we do it, even better. But if you have attention to detail, a collaborative spirit, and a readiness to learn, don't worry, we'll help you make the switch once you arrive.</p>
        </div>
    </div>
</div>