<h1>Job Description</h1>
<div class="table-container">
    <div class="column-left-container">
        <div class="column left">
            <div class="inner-tube">
                <div class="summary">
                    <p>Job Title: <span>Senior Art Director</span></p>
                    <p>Location: <span>Marina Del Rey</span></p>
                    <p>State: <span>California</span></p>
                    <p>Job Type: <span>Full Time Employee</span></p>
                </div>
                <div class="description">
                    <h2>About Us</h2>
					<p>Dr. Schulze’s American Botanical Pharmacy (ABP), located in Marina Del Rey, CA is a privately held business that specializes in the development, manufacture, and distribution of Dr. Schulze’s original herbal formula and programs worldwide. The key to our success is a culture that continually strives for excellence in quality and in the customer experience.</p>
                    <h2>JOB SUMMARY</h2>
                    <p>The role requires a multi-faceted individual who is equally strong in design and the management of people and projects. By bringing dynamic energy to the job, this individual will create and efficiently run department that commands trust and moves with certainty, while delivering engaging designs, on time and with ease.</p>
                    <h2>JOB DESCRIPTION</h2>
                    <p>Senior Art Director formulates concepts and leads staff engaged in executing layout designs for artwork and copy to be presented by visual communications media such as magazines, newspapers, television, interactive posters, in-store POS and packaging. The role of Senior Art Director requires a hands-on manager who actively works on the designs and fully understands that design is in service of communication. In addition, this individual must be knowledgeable of the print production process and is an able representative of ABP with all vendors and suppliers. A key to success is the individual’s ability to work well with all ABP team members, regardless of level, while able to stand for the Art Department’s work, without being attached to the outcome. A strong team player with a can-do attitude is a must.</p>
                    <h2>RESPONSIBILITIES</h2>
                    	<ul>
                    		<li>Manage, lead and restructure the Art Department.</li>
							<li>Interface with key members of the marketing teamto define the creative needs of the various projects and establish timelines to meet those needs.</li>
							<li>Actively participate as a designer on the team.</li>
							<li>Define systems for the day-to-day operations of he Art Department including; efficient management of all assets in the servers.</li>
							<li>Negotiate with vendors to reduce costs and contiually source new vendors that meet ABP’s quality standards at the best prices.</li>
							<li>Manage complete production of all projects incluing; press checks and quality control.</li>
							<li>Inspire an evolving look and feel to maintain frshness, while respecting the integrity and principles of the ABP Brand.</li>
                    	</ul>
                    <h2>EXPERIENCE REQUIRED</h2>
                    	<ul>
	                    	<li>Strong e-commerce experience required in as well as 6-8 years of digital experience.</li>
							<li>At least 4 years of experience leading a team of designers.</li>
							<li>Must have hands-on experience creating exceptional digital brand experiences.</li>
							<li>Strong online design portfolio.</li>
							<li>Ability to think strategically and translate wireframes into tangible and compelling experiences.</li>
							<li>Disseminate standardized approach.</li>
							<li>Well-developed communication skills including ability to effectively articulate design concepts and rationale to other team members and internal business leaders.</li>
							<li>Solid knowledge of the latest versions of applicable programs: Mac OS, Photoshop, Flash, Illustrator, Dreamweaver, InDesign and Fireworks.</li>
							<li>Must have a solid understanding of the strengths and limitations of Flash and HTML5.</li>
							<li>Passion for Design and eagerness to mentor and elevate with other creative team members.</li>
							<li>Entrepreneurial spirit and proactive personality.</li>
                    	</ul>
                    <h2>EDUCATIONAL REQUIREMENTS</h2>
                    	<ul>
	                    	<li>BFA or MFA from a leading 4-year undergraduate or 2-year graduate design program.</li>
							<li>High school diploma required</li>
                    	</ul>

                    <a class="blink1 read-more" href="http://americanbotanicalpharmacy.theresumator.com/apply/wYAXdI/Senior-Art-Director.html">CLICK HERE TO APPLY FOR JOB</a>
                    
                 </div>
            </div>
        </div>
    </div>

    <div class="column right">
        <div class="inner-tube">
            <h4>A few handy tips.</h4>
            <h5>An accurate resume is key.</h5>
            <p>The resume stored in your profile is viewable by recruiters and hiring managers for each position to which you apply. Be sure it realistically represents your skills, knowledge, and experience.</p>
            <h5>What to expect.</h5>
            <p>You'll receive an automated confirmation each time your resume is successfully submitted for an open position. If a recruiter or hiring manager wants to discuss next steps, they'll get in touch using the contact information from your profile or resume.</p>
            <p>You don't necessarily have to be an expert. The best way to understand our company and our customers is to use our products. And if you have passion for what we do and why we do it, even better. But if you have attention to detail, a collaborative spirit, and a readiness to learn, don't worry, we'll help you make the switch once you arrive.</p>
        </div>
    </div>
</div>