<h1>Job Description</h1>
<div class="table-container">
    <div class="column-left-container">
        <div class="column left">
            <div class="inner-tube">
                <div class="summary">
                    <p>Job Title: <span>Senior Recruiter</span></p>
                    <p>Location: <span>Marina Del Rey</span></p>
                    <p>State: <span>California</span></p>
                    <p>Job Type: <span>Full Time Employee</span></p>
                    <p>Job Description:</p>
                </div>
                <div class="description">
                    <h2>About Us</h2>
					<p>Dr. Schulze’s American Botanical Pharmacy is a growth-oriented and purpose-driven distributor of quality herbal products. Our people love challenges, take ownership and thrive in a fast-paced environment. Most important, we are passionate about creating powerful health for all and a culture of service excellence, internally and externally. If you find our philosophy to be a perfect match, please apply for our Senior Recruiter position with competitive compensation. This position will be based in our beautiful headquarters in Marina Del Rey.</p>
                    <h2>EXECUTIVE SUMMARY</h2>
                    <p>We are currently seeking a Contract Recruiter to help fulfill staffing needs as the organization grows. This position is highly visible and current contract will extend at least into 2015. This recruiter will be responsible for managing clients and candidates throughout the full recruiting cycle: sourcing, screening, and managing employer brand in the talent marketplace. The primary focus is to fill officer-level exempt roles as well non-exempt roles by prioritizing workload in a fast-paced business environment. This role reports to the Director of Human Resources and is ideal for a proven talent scout who is passionate about helping organizations win through talent acquisition.</p>
                    <h2>REQUIRED BACKGROUND AND QUALIFICATIONS</h2>
                    	<ul>
                    		<li>
                    			Bachelor’s degree from an accredited university with concentration in Human Resources, Business or Marketing
                    		</li>
                    		<li>
                    			3-5 years of demonstrated recruitment/talent acquisition experience
                    		</li>
                    		<li>
                    			Experience as a strategic partner working with hiring managers and executives to clarify job specifications and optimize job descriptions
                    		</li>
                    		<li>
                    			Partner with HR Director and business managers to fill current hiring needs and identify future needs
                    		</li>
                    		<li>
                    			Manage the offer/negotiation process, working with the HR team, hiring manager, the candidate
                    		</li>
                    		<li>
                    			Facilitate feedback from hiring managers and other interviewers after each interview
                    		</li>
                    		<li>
                    			Represent the organization at job fairs, conferences and in other relevant organizations to attract new talent
                    		</li>
                    		<li>
                    			Participate and contribute to HR organization and Recruiting department special projects
                    		</li>
                    		<li>
                    			Understand the organizational culture and needs as well as the importance of following operational and process requirements
                    		</li>
                    		<li>
                    			Support fully all Diversity, ADA, EEO initiatives, and understand applicable state laws
                    		</li>
                    		<li>
                    			Adaptable with a growth mindset to partner effectively with a variety of work styles
                    		</li>
                    		<li>
                    			Adept at leveraging social media channels and job boards; campus recruitment experience a plus
                    		</li>
                    		<li>
                    			Create key measures of success and provide regular reporting and analysis of recruiting effort 
                    		</li>
                    		<li>
                    			Establish relationships with all levels of an organization to add value via talent strategy
                    		</li>
                    		<li>
                    			Effective verbal and written communication skills with computer proficiency 
                    		</li>
                    	</ul>
                    
                    <a class="blink1 read-more" href=" http://americanbotanicalpharmacy.theresumator.com/apply/hufwl8/Senior-Recruiter.html">CLICK HERE TO APPLY FOR JOB</a>
                    
                 </div>
            </div>
        </div>
    </div>

    <div class="column right">
        <div class="inner-tube">
            <h4>A few handy tips.</h4>
            <h5>An accurate resume is key.</h5>
            <p>The resume stored in your profile is viewable by recruiters and hiring managers for each position to which you apply. Be sure it realistically represents your skills, knowledge, and experience.</p>
            <h5>What to expect.</h5>
            <p>You'll receive an automated confirmation each time your resume is successfully submitted for an open position. If a recruiter or hiring manager wants to discuss next steps, they'll get in touch using the contact information from your profile or resume.</p>
            <p>You don't necessarily have to be an expert. The best way to understand our company and our customers is to use our products. And if you have passion for what we do and why we do it, even better. But if you have attention to detail, a collaborative spirit, and a readiness to learn, don't worry, we'll help you make the switch once you arrive.</p>
        </div>
    </div>
</div>