<div class="content-page faq">
	<h1>FREQUENTLY ASKED QUESTIONS</h1>
	<div class="col1 section1">
		<div class="column1">

			<img class="commondosage1" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/cms/common-dosage/common_dosage_1.png" />
			<ul>
				<li><a href="#area2">1. How Much Is A Dropperful?</a></li>
				<li><a href="#area3">2. What Are The Standard Dosages For The Herbal Formulas?</a></li>
				<li><a href="#area4">3. What Are The Dosages For Children?</a></li>
				<li><a href="#area5">4. What Are The Specific Dosages For Dr. Schulze’s Three Main Foundational Products?</a></li>
				<li><a href="#area6">5. What Happens If I Take Too Much?</a></li>
				<li><a href="#area7">6. What Are The Expiration Dates For The Herbal Formulas?</a></li>
				<li><a href="#area8">7. Is It OK To Take The Formulas If I’m Pregnant Or Nursing?</a></li>
				<a id="area2"></a>
				<li><a href="#area9">8. How Much Alcohol Is In The Formulas?</a></li>
			</ul>
		</div>
	</div>
	<div class="col1 section2">
		<a id="area1"></a>
		<div class="column1">
			<p><span class="start-text">1. How Much Is A Dropperful?</span> A dropperful is whatever comes up in the dropper when you squeeze it. Often, it only looks like about a half a dropperful, but whatever you get when you squeeze the dropper… that’s a dropperful. If you counted it (which would be really boring), it would be about 35 drops. There are also about 35 droppersful in every 1-ounce bottle, and about 70 droppersful in every 2-ounce bottle.</p>
		</div>
	</div>
	<div class="col1 section3">
		<a id="area3"></a>
		<div class="column1">
			<p><span class="start-text">2. What Are The Standard Dosages For The Herbal Formulas?</span> The standard dosage is 2 droppersful, three times a day. Now, if you’re having problems, you can certainly take 4 droppersful, three times a day, or 4 droppersful, five times a day. For immediate relief, you can even increase your dosage to 6 droppersful, 8 droppersful, 10 droppersful or more. Then, once you start getting results, go back to the standard dosage. The bottom line, if you’re not feeling well and your symptoms are persisting, take more herbs and take them more often.  That’s how you heal yourself and create powerful health.</p>
		</div>
	</div>
	<div class="col2 section4">
		<a id="area4"></a>
		<div class="column1">
			<p><span class="start-text">3. What Are The Dosages For Children?</span> Children vary dramatically in size and shape. One 5-year-old can be very different from another. In his clinic, Dr. Schulze found the safest and most effective way to dose children was by weight. After all, we want to adjust their dosage by how much their metabolism can handle. The surest way to do so is by weight. Simply make a fraction and put the child’s weight over 150 pounds. Just look at the following example:</p>
		</div>
		<div class="column2">
			<img class="commondosage2" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/cms/common-dosage/common_dosage_2.png" />
		</div>
	</div>
	<div class="col1 section5">
		<a id="area5"></a>
		<div class="column1">
			<p><span class="start-text">4. what are the specific dosages for dr. schulze’s three main foundational products?</span></p>

			<p><b>SUPERFOOD PLUS:</b> Dr. Schulze suggests 2 tablespoons of SuperFood Plus in a morning drink or 15 tablets in the morning. You can also take 5 tablets, three times a day. That’s the daily dosage. Now, if you’re anemic, if you have low energy or if you have an afternoon slump, then you’ll want to get more nutrition in your body. In this case, Dr. Schulze suggests you take 2 tablespoons and make a SuperFood drink in the morning and AGAIN in the afternoon, or take more tablets.</p>

			<p><b>INTESTINAL FORMULA #1:</b> Dr. Schulze suggests starting with just 1 capsule at night and seeing what happens the next day. If you’re not impressed with the way your bowel works the next morning, take 2 capsules the next night. And then, if you’re still not impressed, go up to 3 capsules the following night, until your bowel is working great.</p>

			<p>Now, if it’s an emergency and you really need to purge, take 2, 3 or 4 capsules with some food. It’s not going to kill you, and it’s going to get whatever is in you… out. Especially if you have something like food poisoning or you ate some bad food. Or, use his Bowel Flush “SHOT”.</p>

			<p><b>ECHINACEA PLUS:</b> Like all of Dr. Schulze’s liquid herbal formulas, the standard dosage is two droppersful, three times per day. That said, there are 12 droppersful of Echinacea in each Cold & Flu Herbal “SHOT”, so it’s fine to increase as needed. Dr. Schulze even suggests using an entire 2-ounce bottle in a day, if you have a severe cold or flu.  He would call that a “heroic dose”, and what he means by this is that sometimes you have to dose yourself with a lot more than your standard dose to get results. And, what you’ll find is that most often, you’ll feel better and you’ll get well. So, don’t be afraid to increase as needed.</p>
		</div>
	</div>
	<div class="col1 section6">
		<a id="area6"></a>
		<div class="column1">
			<p><span class="start-text">5. What Happens If I Take Too Much?</span> Dr. Schulze’s clinical experience with herbs and herbal formulas is that, in the worst-case scenario, you’re going to feel a little sick to your stomach. However, this rarely happens. What usually happens is, when you take larger doses, you get well. So don’t be afraid to really increase your dose when you’re not feeling well. </p>
		</div>
	</div>
	<div class="col1 section7">
		<a id="area7"></a>
		<div class="column1">
			<p><span class="start-text">6. What Are The Expiration Dates For The Herbal Formulas?</span> All of Dr. Schulze’s Specific Formulas are tonics. Unopened, naturally preserved tinctures have an indefinite shelf life. Fifty years from now an unopened bottle of one of Dr. Schulze’s formulas would still be good to use, and just as potent. However, once opened, we recommend consuming them within one year. For the “dry” products (e.g. SuperFood Plus, Intestinal Formula #1, Intestinal Formula #2, HerbalMucil Plus, Detox Tea, K-B Tea and SuperSlim packets), these should be consumed within one year of purchase. And, once opened, they should be consumed within six months.</p>
		</div>
	</div>
	<div class="col2 section8">
		<a id="area8"></a>
		<div class="column1">
			<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/cms/common-dosage/common_dosage_3.png" />
		</div>
		<div class="column2">
			<p><span class="start-text">7. Is It OK To Take The Formulas If I’m Pregnant Or Nursing?</span> Dr. Schulze heard this question 10,000 times or more in his clinic, and his answer was always “YES, you can cleanse and detox during pregnancy, and you can cleanse and detox during nursing.” You just want to use your common sense. Certainly, SuperFood Plus is the best for pregnancy and for nursing, because you’re feeding either the fetus or the baby the best blood and then, once it’s born, the best milk that you can imagine, because you’re fortifying your blood and your milk with SuperFood Plus.</p>

			<p>The Intestinal Formula #1, well, here’s where the common sense comes in. You shouldn’t be sending yourself into an extensive, intensive, cathartic bowel movement in your eighth-and-a-half month of pregnancy, unless you want to bring on labor. That said, you can use Intestinal Formula #1 even in your third trimester; that’s no problem. Just don’t cause some major bowel catharsis. Keep it simple and lower your dosage. </p>

			<p>Once you have your baby, if you want to use Intestinal Formula #1, that’s fine. But remember, any herb you take will get through your milk into your baby on a reduced level. So, you’re also going to be treating your baby, too, which is great, because if your baby has an infection, you can take high dosages of Echinacea Plus, and it will get through the breast milk into your child. So yes, you can do all the programs when you’re pregnant and when you’re nursing. Just use your head and your good common sense.</p>
		</div>
	</div>
	<div class="col1 section9">
		<a id="area9"></a>
		<div class="column1">
			<p><span class="start-text">8. How Much Alcohol Is In The Formulas?</span> The base of the majority of Dr. Schulze’s herbal formulas are mostly distilled water, but most of them do contain organic, pure-grain alcohol as well. However, the amount of alcohol in the average dose of tincture is equal to the amount of alcohol in a ripe banana. 

			<p>This dosage has been tested on people who are alcohol sensitive with no adverse reactions. It is also a safe amount for anyone in a 12-Step Program or Alcoholics Anonymous. If you’re still concerned about the alcohol, you can place the tincture in a cup, pour boiling water into the cup, and the alcohol will evaporate in seconds..</p>
		</div>
	</div>
</div>

