<h1>Job Description</h1>
<div class="table-container">
    <div class="column-left-container">
        <div class="column left">
            <div class="inner-tube">
                <div class="summary">
                    <p>Job Title: <span>Call Center Manager</span></p>
                    <p>Location: <span>Marina Del Rey</span></p>
                    <p>State: <span>California</span></p>
                    <p>Job Type: <span>Full Time Employee</span></p>
                    <p>Job Description:</p>
                </div>
                <div class="description">
                    
                    <h2>About Us</h2>
					<p>Dr. Schulze’s American Botanical Pharmacy is a growth-oriented distributor of quality herbal products. Our people love challenges, take ownership and thrive in a fast-paced environment. Most important, we are passionate about creating powerful health for all and a culture of customer service excellence. If you find our philosophy to be a perfect match, please apply for our Contact Center Manager position with competitive compensation and growth potential. This position will be based in our beautiful headquarters in fresh and breezy Marina Del Rey. </p>
                    <h2>SUMMARY</h2>
                    <p>Oversees the call center operation and leads a team of agents to provide high quality customer service. The position requires strong leadership capabilities, the ability to manage a diverse team, and a good understanding of call center operations.</p>
	                    <p>Our inbound Call Center has over 30 representatives averaging 800 calls per day and in our peak season takes more than 1,500 calls a day!</p>
                    <h2>Essential Duties and Responsibilities include the following:</h2>
                    	<ul>
                    		<li>
                    			Provides daily leadership, management and coaching of call center team
                    		</li>
                    		<li>
                    			Hires, leads and manages a diverse workforce in a call center environment
                    		</li>
                    		<li>
                    			Supports strategy for the call center to achieve corporate objectives
                    		</li>
                    		<li>
                    			Creates a positive work environment focused on meeting and exceeding customer service and productivity expectations
                    		</li>
                    		<li>
                    			Supports policies, standards, performance criteria and metrics to continuously improve productivity, service quality and client and employee retention
                    		</li>
                    		<li>
                    			Analyzes call center metrics, service levels and other key performance indicators
                    		</li>
                    		<li>
                    			Other duties as assigned
                    		</li>
                     	</ul>
                     	
                     	<h2>Education/Experience</h2>
                     		<ul>
	                     		<li>Associate’s degree or equivalent with at least one year of related experience </li>
                     		</ul>
                     		
                    
                     <a class="blink1" href="http://americanbotanicalpharmacy.theresumator.com/apply/J6E5XE/Call-Center-Manager.html">CLICK HERE TO APPLY FOR JOB</a>
                    
                 </div>
            </div>
        </div>
    </div>

    <div class="column right">
        <div class="inner-tube">
            <h4>A few handy tips.</h4>
            <h5>An accurate resume is key.</h5>
            <p>The resume stored in your profile is viewable by recruiters and hiring managers for each position to which you apply. Be sure it realistically represents your skills, knowledge, and experience.</p>
            <h5>What to expect.</h5>
            <p>You'll receive an automated confirmation each time your resume is successfully submitted for an open position. If a recruiter or hiring manager wants to discuss next steps, they'll get in touch using the contact information from your profile or resume.</p>
            <p>You don't necessarily have to be an expert. The best way to understand our company and our customers is to use our products. And if you have passion for what we do and why we do it, even better. But if you have attention to detail, a collaborative spirit, and a readiness to learn, don't worry, we'll help you make the switch once you arrive.</p>
        </div>
    </div>
</div>