<h1>Job Description</h1>
<div class="table-container">
    <div class="column-left-container">
        <div class="column left">
            <div class="inner-tube">
                <div class="summary">
                    <p>Job Title: <span>Contact Center Representative (Full Time)</span></p>
                    <p>Location: <span>Marina Del Rey</span></p>
                    <p>State: <span>California</span></p>
                    <p>Job Type: <span>Full Time Employee</span></p>
                    <p>Job Description:</p>
                </div>
                <div class="description">
										<h2>JOB SUMMARY:</h2>
					<p>We are growing and need you to join our winning team! Our Company is located in Marina del Rey, CA and is the sole distributor of Dr. Schulze’s original herbal formula and natural healing routines worldwide. As more and more people turn towards creating powerful health, they reach out to our Call Center seeking ways to include our products into their lives.</p>
					

					<h2>KEY QUALIFICATIONS:</h2>
                    	<ul>
	                    	<li>
	                    	Customer Service oriented
	                    	</li>
                    		<li>
                    			 Proven ability to consistently be effective and efficient in answering inbound calls with exceptional quality
                    		</li>
                    		<li>
                    			Attention to detail in capturing customer requests with the ability to clearly and concisely document customer accounts
                    		</li>
                    		<li>
                    			Ability to be genuine, patient and empathetic as needed
                    		</li>
                    		<li>
                    		Actively listen and effectively communicate with new and existing customers
                    		</li>
                    		
                    	</ul>
					<h2>JOB DESCRIPTION:</h2>
					<p>The Contact Center Representative is the voice of the company and your primary role is to accurately answer product related questions and guide our customers through the product ordering process.  You will need to be helpful and courteous by nature.  Your success will depend on your ability to answer inbound calls with exceptional phone etiquette and proper communication skills consistently. You must also follow internal processes to ensure that we are consistent in the service that we provide.  As a strong advocate of Dr. Schulze’s message and programs, you are responsible for upholding our high standards of product quality and service excellence.</p>
                    <h2>ADDITIONAL REQUIREMENTS:</h2>
                    <ul>
                    	<li>Minimum of 1 year of customer service contact center experience </li>
						<li>Adaptable and flexible with schedule</li>
						<li>Team player that is adaptable to take on additional tasks as needed</li>
						<li>Familiarity with standard email office applications</li>
						<li>Type minimum of 45 words per minute</li>
						<li>Higher learning experience preferred</li>
						<li>High School Diploma required.</li>
                    </ul>
                                        <h2>CANDIDATE SUBMISSIONS</h2>
                    <b>Please submit resume with cover letter directly to <a style="color:#666666;" href="mailto:someone@example.com"> Recruit@herbdoc.com</a></b>
                    <h2>Work hours</h2>
                    <h2>Call Center hours are 6:00am--7:00pm Monday through Saturday; Sunday 7:00am-3:30pm. Schedules are determined by management & vary based on scheduling needs.</h2>
                    <h2>Looking for full time and part time employees.</h2>
                    
                     <a class="blink1" href="http://americanbotanicalpharmacy.theresumator.com/apply/NZtHZ3/Call-Center-Representative-Full-Time.html">CLICK HERE TO APPLY FOR JOB</a>
                    
                 </div>
            </div>
        </div>
    </div>

    <div class="column right">
        <div class="inner-tube">
            <h4>A few handy tips.</h4>
            <h5>An accurate resume is key.</h5>
            <p>The resume stored in your profile is viewable by recruiters and hiring managers for each position to which you apply. Be sure it realistically represents your skills, knowledge, and experience.</p>
            <h5>What to expect.</h5>
            <p>You'll receive an automated confirmation each time your resume is successfully submitted for an open position. If a recruiter or hiring manager wants to discuss next steps, they'll get in touch using the contact information from your profile or resume.</p>
            <p>You don't necessarily have to be an expert. The best way to understand our company and our customers is to use our products. And if you have passion for what we do and why we do it, even better. But if you have attention to detail, a collaborative spirit, and a readiness to learn, don't worry, we'll help you make the switch once you arrive.</p>
        </div>
    </div>
</div>