<h1>Job Description</h1>
<div class="table-container">
    <div class="column-left-container">
        <div class="column left">
            <div class="inner-tube">
                <div class="summary">
                    <p>Job Title: <span>Human Resources Manager </span></p>
                    <p>Location: <span>Marina Del Rey</span></p>
                    <p>State: <span>California</span></p>
                    <p>Job Type: <span>Full Time Employee</span></p>
                    <p>Job Description:</p>
                </div>
                <div class="description">
                    
                    <h2>About Us</h2>
					<p>Dr. Schulze’s American Botanical Pharmacy is a growth-oriented and purpose-driven distributor of quality herbal products. Our people love challenges, take ownership and thrive in a fast-paced environment. Most important, we are passionate about creating powerful health for all and a culture of service excellence, internally and externally. If you find our philosophy to be a perfect match, please apply for our HR Manager position with highly competitive compensation and growth potential. This position will be based in our beautiful headquarters in Marina Del Rey. </p>
                    <h2>EXECUTIVE SUMMARY</h2>
                    <p>We have an incredibly exciting opportunity for a human resources leader who is passionate about the HR profession. The HR manager role serves a key strategic function and is highly visible within the organization and offers growth potential. The HR manager reports to Director of HR and manages two HR coordinators.</p>
                    <h2>QUALIFICATIONS</h2>
                    	<ul>
                    		<li>
                    			At least 7-10 years of human resources experience functioning in a generalist capacity.
                    		</li>
                    		<li>
                    			Bachelor’s degree in Human Resources, Business or related field. SHRM certification a plus.
                    		</li>
                    		<li>
                    			Must have strong background in talent acquisition, leadership coaching, employee engagement, performance management and change management.
                    		</li>
                    		<li>
                    			Subject matter expertise on CA and Federal employment practices, policies, legal & EEOC guidelines, as well as wage & hour, payroll and benefits administration. 
                    		</li>
                    		<li>
                    			Compliance in all areas of benefits required including, but not limited to ERISA, COBRA, HIPAA, ACA, and ability to identify and comply with new state requirements as regulations are enacted
                    		</li>
                    		<li>
                    			Strong administrative background with FMLA, ADA, STD, LTD, bereavement, CFRA 
                    		</li>
                       	</ul>
                     <h2>RESPONSIBILITIES</h2>
                     	<ul>
                     		<li>
                    			Participate in business leadership meetings as a strategic partner to identify human resource implications and provide creative solutions to enhance individual and organizational performance
                    		</li>
                    		<li>
                    			Build strategic relationships with business unit managers to increase employee engagement and maintain positive employee relations. Develop creative and innovative solutions for improvement
                    		</li>
                    		<li>
                    			Provide leadership, act as mentor and brand ambassador for both HR department and organization
                    		</li>
                    		<li>
                    			Manage effective employee communication channels to ensure consistent organizational messages
                    		</li>
                    		<li>
                    			Provide leadership coaching, employee counseling to corrective action fairly and consistently 
                    		</li>
                    		<li>
                    			Manage assigned client group in annual goal setting and performance evaluation process
                    		</li>
                    		<li>
                    			Manage employee engagement programs and conduct surveys by partnering with senior leadership
                    		</li>
                    		<li>
                    			Champion talent acquisition and management process from ATS, recruiting to succession planning
                    		</li>
                    		<li>
                    			Establish employment brand to attract talent by leveraging web strategy such as social media 
                    		</li>
                    		<li>
                    			Help create HR success indicators and provide regular reporting and analysis of recruiting effort 
                    		</li>
                    		<li>
                    			Be a strategic change agent with strong HR project management skills; superior computer literacy                     	
                    		</li>
                     	</ul>

                    <a class="blink1 read-more" href="http://americanbotanicalpharmacy.theresumator.com/apply/nBP5Sc/Human-Resources-Manager.html">CLICK HERE TO APPLY FOR JOB</a>
                    
                    
                 </div>
            </div>
        </div>
    </div>

    <div class="column right">
        <div class="inner-tube">
            <h4>A few handy tips.</h4>
            <h5>An accurate resume is key.</h5>
            <p>The resume stored in your profile is viewable by recruiters and hiring managers for each position to which you apply. Be sure it realistically represents your skills, knowledge, and experience.</p>
            <h5>What to expect.</h5>
            <p>You'll receive an automated confirmation each time your resume is successfully submitted for an open position. If a recruiter or hiring manager wants to discuss next steps, they'll get in touch using the contact information from your profile or resume.</p>
            <p>You don't necessarily have to be an expert. The best way to understand our company and our customers is to use our products. And if you have passion for what we do and why we do it, even better. But if you have attention to detail, a collaborative spirit, and a readiness to learn, don't worry, we'll help you make the switch once you arrive.</p>
        </div>
    </div>
</div>