<h1>Job Description</h1>
<div class="table-container">
    <div class="column-left-container">
        <div class="column left">
            <div class="inner-tube">
                <div class="summary">
                    <p>Job Title: <span>Warehouse Floor - Team Member</span></p>
                    <p>Location: <span>Marina Del Rey</span></p>
                    <p>State: <span>California</span></p>
                    <p>Job Type: <span>Full Time Employee</span></p>
                    <p>Job Description:</p>
                </div>
                <div class="description">
                    <h2>About Us:</h2>
					<p>Dr. Schulze's American Botanical Pharmacy (ABP), located in Marina del Rey, CA, is a privately held business that specializes in the development, manufacture, and distribution of Dr. Schulze's original herbal formula and programs worldwide. The key to our success is a culture that continually strives for excellence in quality and in the customer experience.  </p>
         
                    <h2>JOB DESCRIPTION:</h2>
                    <p>Progressive, quality conscious company is searching for an enthusiastic and positive individual to work in a warehouse setting with standard warehouse equipment such as scanners, hand trucks, tape dispensers and box cutters. This individual must be able to safely and properly perform the physical duties associated with the job, including but not limited to reaching and bending frequently, standing in upright positions for long hours, handling, lifting and moving objects up to 50 pounds. The business hours for the warehouse generally are 8 AM to 4:30 PM. </p>
                    
                    <h2>See Job Responsibilities below for more detail:</h2>
                    <h2>Some job duties and functions are, but not limited to, as follows:</h2>
                    	<ul>
                    		<li>
                    			Picking orders
                    		</li>
                    		<li>
                    			Checking orders
                    		</li>
                    		<li>
                    			Packaging orders
                    		</li>
                    		<li>
                    			Maintaining and organizing work areas and work stations 
                    		</li>
                    		<li>
                    			Kit assembly
                    		</li>
                    		<li>
                    			Package handling                    	
                    		</li>
                    		<li>
								Order processing               		
							</li>
                    		<li>
                    			As well as other tasks deemed necessary by ABP supervision or management
                    		</li>
                    		<li>
                    			Some experience working in a warehouse, distribution, production environment
                    		</li>
                    		<li>High School Diploma/GED</li>
                    	</ul>
                    	 
                    	                     		
                    <a class="blink1 read-more" href=" http://americanbotanicalpharmacy.applytojob.com/apply/a4wCrh/Warehouse-Floor-Team-Member.html">CLICK HERE TO APPLY FOR JOB</a>
                    
                 </div>
            </div>
        </div>
    </div>

    <div class="column right">
        <div class="inner-tube">
            <h4>A few handy tips.</h4>
            <h5>An accurate resume is key.</h5>
            <p>The resume stored in your profile is viewable by recruiters and hiring managers for each position to which you apply. Be sure it realistically represents your skills, knowledge, and experience.</p>
            <h5>What to expect.</h5>
            <p>You'll receive an automated confirmation each time your resume is successfully submitted for an open position. If a recruiter or hiring manager wants to discuss next steps, they'll get in touch using the contact information from your profile or resume.</p>
            <p>You don't necessarily have to be an expert. The best way to understand our company and our customers is to use our products. And if you have passion for what we do and why we do it, even better. But if you have attention to detail, a collaborative spirit, and a readiness to learn, don't worry, we'll help you make the switch once you arrive.</p>
        </div>
    </div>
</div>