<h1>Job Description</h1>
<div class="table-container">
    <div class="column-left-container">
        <div class="column left">
            <div class="inner-tube">
                <div class="summary">
                    <p>Job Title: <span>Warehouse Floor Supervisor</span></p>
                    <p>Location: <span>Marina Del Rey</span></p>
                    <p>State: <span>California</span></p>
                    <p>Job Type: <span>Full Time Employee</span></p>
                </div>
                <div class="description">
                    <h2>About Us</h2>
					<p>Dr. Schulze’s American Botanical Pharmacy (ABP), located in Marina Del Rey, CA is a privately held business that specializes in the development, manufacture, and distribution of Dr. Schulze’s original herbal formula and programs worldwide. The key to our success is a culture that continually strives for excellence in quality and in the customer experience. </p>
                    <h2>JOB SUMMARY</h2>
                    <p>Established, growing, dynamic manufacturer with a distribution center in Marina Del Rey is looking for a Warehouse Supervisor who will oversee and support all warehouse floor functions, and must have good communication and leadership skills.  Experience in a fast paced, order fulfilment, warehouse environment is preferred.  This position reports to the Logistics and Distribution Manager. Please refer to Responsibilities listed below. </p>
                  
                    <h2>RESPONSIBILITIES</h2>
                    	<ul>
                    		<li>Monitor metrics, standards with regards to performance and behavior.</li>
							<li>Evaluate Warehouse floor processes, systems and tasks, and develop and implement improvements based on need, priority and value.</li>
							<li>Demonstrate consistent ability to learn and adapt to changing demands of the work environment, assess needs and report accurately to the manager and/or arrive at sound business decisions.</li>
							<li>Oversee and monitor order processing from technology (intercompany or outside support) to document processing to ensure proper and best distribution practices.</li>
							<li>Develop and maintain a proper and consistent line of communication with all Warehouse team members, internal and external departments.</li>
							<li>Manage competing work priorities and supervise effectively in areas where standard operating procedures may not exist.</li>
							<li>Understand, protect and strengthen the brand in the area of customer experience.</li>
							<li>Be a strong brand ambassador in and outside the company.</li>
							
                    	</ul>
                    <h2>EXPERIENCE REQUIRED</h2>
                    	<ul>
	                    	<li>At least 5 years of supervision experience in a warehouse and distribution environment with an emphasis on order fulfilment.</li>
							<li>Proficient in MS Applications, such as Excel, Word, and/or Outlook, as well as Warehouse Management Systems.</li>
                    	</ul>
                   
                    <a class="blink1 read-more" href="http://americanbotanicalpharmacy.applytojob.com/apply/xZrGKT/Warehouse-Floor-Supervisor.html">CLICK HERE TO APPLY FOR JOB</a>
                    
                 </div>
            </div>
        </div>
    </div>

    <div class="column right">
        <div class="inner-tube">
            <h4>A few handy tips.</h4>
            <h5>An accurate resume is key.</h5>
            <p>The resume stored in your profile is viewable by recruiters and hiring managers for each position to which you apply. Be sure it realistically represents your skills, knowledge, and experience.</p>
            <h5>What to expect.</h5>
            <p>You'll receive an automated confirmation each time your resume is successfully submitted for an open position. If a recruiter or hiring manager wants to discuss next steps, they'll get in touch using the contact information from your profile or resume.</p>
            <p>You don't necessarily have to be an expert. The best way to understand our company and our customers is to use our products. And if you have passion for what we do and why we do it, even better. But if you have attention to detail, a collaborative spirit, and a readiness to learn, don't worry, we'll help you make the switch once you arrive.</p>
        </div>
    </div>
</div>