<h1>Job Description</h1>
<div class="table-container">
    <div class="column-left-container">
        <div class="column left">
            <div class="inner-tube">
                <div class="summary">
                    <p>Job Title: <span>eCommerce Manager</span></p>
                    <p>Location: <span>Marina Del Rey</span></p>
                    <p>State: <span>California</span></p>
                    <p>Job Type: <span>Full Time Employee</span></p>
                    <p>Job Description:</p>
                </div>
                <div class="description">
	                <h2>Looking for….?</h2>
						<ul>
							<li>Healthy work/life balance</li>
							<li>Salary commensurate with experience</li>
							<li>Bonus opportunity</li>
							<li>Building a career being mentored by an accomplished VP of eCommerce</li>
							<br>
						</ul>
						<p>If yes, please read on. If no, thank you.</p>
	                    <h2>ABOUT US</h2>
					<p>Our company is located in Marina Del Rey, CA, established in 1994 and growing steadily ever since, specializes in the development, manufacture, and distribution of Dr. Schulze’s original herbal formula and programs worldwide. Our commitment to health and healing using powerful and natural herbs speaks to what we do AND how we do it.  Our passion for quality, product and service excellence makes us a leader in natural health and wellness industry. </p>
					<h2>ABOUT THE POSITION</h2>
					<p>This position is responsible for the management of our eCommerce business, specifically through the execution of digital marketing strategies. In addition, the candidate will support the company in bringing the ecommerce platform to the next level, ensuring that the product platform evolves in a way that increases market appeal, user satisfaction, and revenue.</p>
					
                    <h2>RESPONSIBILITIES INCLUDE</h2>
                    	<ul>
                    		<li>
								Develop and execute site marketing calendar.							
							</li>
                    		<li>
                    			Manage, maintain, and launch web promotions. 
                    		</li>
                    		<li>
                    			Oversee online store platform, including feature functionality, user experience, landing page optimization, effective online merchandising of products, promotions, and site refreshes               
                    		</li>
                    		<li>
                    			Manage web operations and projects, and conduct competitive analysis
                    		</li>
                    		<li>
                    			Responsible for reporting e-commerce KPI data and working with cross functional business unit leaders in recommending changes to increase visitors, improve conversion rates, capturing larger average order sizes.
                    		</li>
                    		<li>
                    			Manage marketing promotions and integrated programs.  Execute programs and coordinate with cross-functional programs.
                    		</li>
                    		<li>
                    			Manage, analyze, and improve performance of marketing channels via email, SEM/SEO, social media, and other web-based marketing programs
                    		</li>
                    	</ul>
						
						<h2>Skills and Experience</h2>
                    	<ul>
                    		<li>
                    			Bachelor’s degree required; MBA preferred
                    		</li>
                    		<li>
                    			Minimum 3 years of experience working on an e-commerce website                 		
                    		</li>
                    		<li>
                    			Google Analytics experience preferred
                    		</li>
                    		<li>
                    			Intermediate to advanced Excel proficiency	
                    		</li>
                    		<li>
                    			Strong verbal and written communication skills
                    		</li>
						</ul>
						

                    <a class="blink1 read-more" href="http://americanbotanicalpharmacy.applytojob.com/apply/sHcwQq/Ecommerce-Manager.html">CLICK HERE TO APPLY FOR JOB</a>
                    
                    
                 </div>
            </div>
        </div>
    </div>

    <div class="column right">
        <div class="inner-tube">
            <h4>A few handy tips.</h4>
            <h5>An accurate resume is key.</h5>
            <p>The resume stored in your profile is viewable by recruiters and hiring managers for each position to which you apply. Be sure it realistically represents your skills, knowledge, and experience.</p>
            <h5>What to expect.</h5>
            <p>You'll receive an automated confirmation each time your resume is successfully submitted for an open position. If a recruiter or hiring manager wants to discuss next steps, they'll get in touch using the contact information from your profile or resume.</p>
            <p>You don't necessarily have to be an expert. The best way to understand our company and our customers is to use our products. And if you have passion for what we do and why we do it, even better. But if you have attention to detail, a collaborative spirit, and a readiness to learn, don't worry, we'll help you make the switch once you arrive.</p>
        </div>
    </div>
</div>