<h1>Job Description</h1>
<div class="table-container">
    <div class="column-left-container">
        <div class="column left">
            <div class="inner-tube">
                <div class="summary">
                    <p>Job Title: <span>Marketing Program Manager</span></p>
                    <p>Location: <span>Marina Del Rey</span></p>
                    <p>State: <span>California</span></p>
                    <p>Job Type: <span>Full Time Employee</span></p>
                    <p>Job Description:</p>
                </div>
                <div class="description">
                    <h2>ABOUT US</h2>
                    <p>Dr. Schulze's American Botanical Pharmacy (ABP) located in Marina del Rey, CA, is a privately held business that specializes in the development, manufacture, and distribution of Dr. Schulze's original herbal formula and programs worldwide.</p>
                    <h2>MARKETING PROGRAM MANAGER ROLE</h2>
                    <p>At ABP, the Marketing Manager being talented, nimble and self-driven is necessary, but it isn’t enough. With responsibilities that encompass the development, launch and management of marketing initiatives, the Marketing Manager is a project leader – always ahead of the curve, rather than chasing it. The ideal candidate knows how to take ownership of multiple projects within a team dynamic and see them through to completion. A key to success in the Marketing Manager role is the balance of being analytical so as to understand your programs and make needed adjustments, while at the same time being innovative to overcome challenges and identify opportunities. Above all, the abilities and work ethic of the Marketing Manager are always in support of positive change and growth at ABP as both a business and a culture.</p>
                    <h2>WHAT YOU WILL NEED:</h2>
                    <p>BA/BS in a marketing related field 5 years MINIMUM experience in marketing Macintosh Proficient and PC Proficient in MS Office (Word, Excel, PowerPoint).</p>
                    <h2>WHAT YOU WILL DO:</h2>
                    <p>Develop and execute marketing campaigns that build memberships and revenue for continuity and loyalty programs</p>
                    <h2>WHAT YOU WILL DO:</h2>
                    <p>Develop and execute marketing campaigns that build memberships and revenue for continuity and loyalty programs</p>
                    <p>Communicate through Direct-Mail, E-Mail and utilization of our inside Call-Center</p>
                    <p>Manage multiple projects in various states of completion simultaneously</p>
                    <p>Manage to specified outcomes for revenue</p>
                    <p>Build Excel tracking systems on campaigns for analysis</p>
                    <p>Provide solutions to marketing challenges through real-time campaign analysis</p>
                    <p>Be a self-starter and work well with others</p>
                    <p>Be of service to others both inside and outside the company</p>
                    <p>Be flexible and embrace change</p>
                    <p>Cultivate collaboration across businesses and departments</p>
                    <p>Challenge yourself to always grow</p>
                </div>
            </div>
        </div>
    </div>

    <div class="column right">
        <div class="inner-tube">
            <h4>A few handy tips.</h4>
            <h5>An accurate resume is key.</h5>
            <p>The resume stored in your profile is viewable by recruiters and hiring managers for each position to which you apply. Be sure it realistically represents your skills, knowledge, and experience.</p>
            <h5>What to expect.</h5>
            <p>You'll receive an automated confirmation each time your resume is successfully submitted for an open position. If a recruiter or hiring manager wants to discuss next steps, they'll get in touch using the contact information from your profile or resume.</p>
            <p>You don't necessarily have to be an expert. The best way to understand our company and our customers is to use our products. And if you have passion for what we do and why we do it, even better. But if you have attention to detail, a collaborative spirit, and a readiness to learn, don't worry, we'll help you make the switch once you arrive.</p>
        </div>
    </div>
</div>