<table id="Mail_Footer" width="600" height="80" border="0" cellpadding="0" cellspacing="0" style="margin-top:-12px;">
	<tr>
		<td width="42" height="37" colspan="3" style="border-left:solid thin #000;background-color:#6d6e71;">
			</td>
		<td width="105" height="37" colspan="2" style="background-image: url();font-family: Arial, Helvetica, Verdana, sans-serif;font-size:11px;text-align:left;color:white;line-height:0px;background-color:#6d6e71;padding-left:15px;">
<a style="color:white;font-style: normal;text-decoration: none;" href="https://www.herbdoc.com/privacy-policy">Privacy Policy</a></td>
		<td width="95" height="37" colspan="2" style="background-image: url();font-family: Arial, Helvetica, Verdana, sans-serif;font-size:11px;text-align:left;color:white;line-height:0px;background-color:#6d6e71;">
<a style="color:white;font-style: normal;text-decoration: none;" href="mailto:websupport@herbdoc.com?Subject=Help%20Request%20-%20Welcome%20Email">Get Help</a></td>
		<td width="358" height="37" colspan="11" style="background-image: url();font-family: Arial, Helvetica, Verdana, sans-serif;font-size:11px;text-align:left;color:white;line-height:0px;background-color:#6d6e71;border-right:solid thin #000;">
&copy;2015 American Botanical Pharmacy. All Right Reserved.</td>
	</tr>
	<tr>
		<td width="600" height="99" colspan="18" style="background-image: url();font-family: Arial, Helvetica, Verdana, sans-serif;font-size:9px;text-align:left;color:#333;line-height:0px;vertical-align:top;letter-spacing:0.5px;border-left:solid thin #000;border-right:solid thin #000;border-bottom:solid thin #000;padding-left:15px;">
<span style="display:block;padding:25px 0 0 40px;">American Botanical Pharmacy. P.O. Box 9699, Marina Del Rey, CA 90295</span>
<span style="display:block;padding:30px 0 0 40px;">Please do not reply to this email. If you need to contact us</span><span style="display:block;padding:10px 0 0 40px;">with questions or concerns, please <a style="color:#333;font-style: normal;text-decoration: underline;" href="mailto:websupport@herbdoc.com?Subject=Customer%20Email%20-%20Contact%20Us">click here</a>.</span></td>
  </tr>
</table>