<div style="background:#EAEAEA; text-align:center; width:100%; padding:10px 0; font-size:10px;">
<address class="copyright">Copyright © 2015 American Botanical Pharmacy.<!--<?php echo Mage::app()->getStore()->getName(); ?>.--> All Rights Reserved.<br> 
						<a href="https://www.herbdoc.com/store-directions"  style="text-decoration: underline; color: #282828;">Retail Location:</a>&nbsp; <?php echo Mage::getStoreConfig('general/store_information/address'); ?></address>
</div>