<table id="header_vc2" width="600" height="60" border="0" cellpadding="0" cellspacing="0" style="border-top:thin solid #000;border-right:thin solid #000;border-left:thin solid #000;">
	<tr>
		<td width="45" height="30" style="background-color:#e6e7e8;">
			</td>
		<td width="126" height="60" rowspan="2">
			<img src="http://americanbotanicalpharmacy.dmplocal.com/dsc/collateral/header_vc2_02.jpg" width="126" height="60" alt="herbdoc.com" border="0" align="top"></td>
		<td width="108" height="30" style="background-color:#e6e7e8;">
			</td>
		<td width="100" height="30" style="background-image: url(http://americanbotanicalpharmacy.dmplocal.com/dsc/collateral/New-Account-Set-up_A_v6_03.jpg);font-family: Arial, Helvetica, Verdana, sans-serif;font-size:12px;font-weight:bold;text-align:left;background-color:#e6e7e8;">
<a style="text-decoration:none; color:#000000;" href="https://www.herbdoc.com/store/"> Shop</a>
			</td>
		<td width="101" height="30" style="background-image: url(http://americanbotanicalpharmacy.dmplocal.com/dsc/collateral/New-Account-Set-up_A_v6_04.jpg);font-family: Arial, Helvetica, Verdana, sans-serif;font-size:12px;font-weight:bold;text-align:left;background-color:#e6e7e8;">
<a style="text-decoration:none; color:#000000;" href="https://www.herbdoc.com/learn"> Learn</a>
			</td>
		<td width="118" height="30" style="background-image: url(http://americanbotanicalpharmacy.dmplocal.com/dsc/collateral/New-Account-Set-up_A_v6_05.jpg);font-family: Arial, Helvetica, Verdana, sans-serif;font-size:12px;font-weight:bold;text-align:left;background-color:#e6e7e8;">
<a style="text-decoration:none; color:#000000;" href="https://www.herbdoc.com/dr-schulze">Dr. Schulze</a>
			</td>
	</tr>
	<tr>
		<td width="45" height="30">
			</td>
		<td width="108" height="30">
			</td>
		<td width="319" height="30" colspan="3">
			</td>
	</tr>
</table>