<div class="content section1-2">
    <div class="table">
        <div class="table-row">
            <div class="table-cell">
                <div class="inner-tube">
                    <h3>SPECIFICS</h3>
                    <h4>Designed to focus on and support specific areas of the body.</h4>
                    <div class="separator"></div>
                </div>
            </div>
            <div class="table-cell">
                <div class="inner-tube">
                    <ul>
                        <li><a href="/protect-formula.html">Protect Formula</a></li>
                        <li><a href="/brain-formula.html">Brain Formula</a></li>
                        <li><a href="/heart-formula-2oz.html">Heart Formula</a></li>
                        <li><a href="/air-detox.html">Air Detox</a></li>
                        <li><a href="/daily-oral-therapy.html">Daily Oral Therapy</a></li>
                        <li><a href="/super-tonic.html">SuperTonic</a></li>
                        <li><a href="/female-formula-2oz.html">Female Formula</a></li>
                        <li><a href="/prostate-formula.html">Prostate Formula</a></li>
                        <li><a href="/deep-tissue.html">Deep Tissue</a></li>
                        
                        <!--<li><a href="/specifics.html">Protect Formula</a></li>
                        <li><a href="/specifics.html">Brain Formula</a></li>
                        <li><a href="/specifics.html">Heart Formula</a></li>
                        <li><a href="/specifics.html">Air Detox</a></li>
                        <li><a href="/specifics.html">Daily Oral Therapy</a></li>
                        <li><a href="/specifics.html">SuperTonic</a></li>
                        <li><a href="/specifics.html">Female Formula</a></li>
                        <li><a href="/specifics.html">Prostate Formula</a></li>
                        <li><a href="/specifics.html">Deep Tissue</a></li>-->
                    </ul>
                </div>
                <div class="more-products"><a href="/specifics.html">More Products</a></div>
            </div>
            <div class="table-cell">
                <div class="img-container"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) ?>/wysiwyg/home/section1-2.png" alt="PROTECT Formula" /></div>
                <div class="view-all"><a class="blink1" href="/specifics.html">VIEW ALL</a></div>
            </div>
        </div>
    </div>
</div>
