<div class="content section1-1">
    <div class="article-container">
        <article class="article article1">
            <div class="inner-tube">
                <h3>Nutrition</h3>
                <h4>Everyone needs to flood their body with more nutrition!</h4>
                <div class="separator"></div>
                <ul>
	                <li><a href="/superfood-plus.html">SuperFood Plus</a></li>
                    <li><a href="/superfood-100.html">SuperFood 100</a></li>
                    <li><a href="/superfood-bars-12-pack.html">SuperFood Bars</a></li>
                    <li class="more-products"><a href="/nutrition.html">More Products</a></li>
                    
                    <!--<li><a href="/nutrition.html">SuperFood Plus</a></li>
                    <li><a href="/nutrition.html">SuperFood 100</a></li>
                    <li><a href="/nutrition.html">SuperFood Bars</a></li>
                    <li class="more-products"><a href="/nutrition.html">More Products</a></li>-->
                </ul>
                <div class="img-container-outertube"><div class="img-container"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) ?>/wysiwyg/home/section1-1_article1.png" alt="SuperFood Plus" /></div></div>
                <div class="view-all"><a class="blink1" href="/nutrition.html">VIEW ALL</a></div>
            </div>
        </article>
        <article class="article article2">
            <div class="inner-tube">
                <h3>Eliminate</h3>
                <h4>Blockage is the root of all disease. Get the waste out!</h4>
                <div class="separator"></div>
                <ul>
                    <li><a href="/intestinal-formula-1.html">Intestinal Formula #1</a></li>
                    <li><a href="/intestinal-formula-2.html">Intestinal Formula #2</a></li>
                    <li><a href="/bowel-flush-shot-3-pack.html">Bowel Flush “SHOT”</a></li>
                    <li class="more-products"><a href="/eliminate.html">More Products</a></li>
                    
                    <!--<li><a href="/eliminate.html">Intestinal Formula #1</a></li>
                    <li><a href="/eliminate.html">Intestinal Formula #2</a></li>
                    <li><a href="/eliminate.html">Bowel Flush “SHOT”</a></li>
                    <li class="more-products"><a href="/eliminate.html">More Products</a></li>-->
                </ul>
                <div class="img-container-outertube"><div class="img-container"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) ?>/wysiwyg/home/section1-1_article2.png" alt="Intestinal Formula" /></div></div>
                <div class="view-all"><a class="blink1" href="/eliminate.html">VIEW ALL</a></div>
            </div>
        </article>
          <article class="article article4">
            <div class="inner-tube">
                <h3>Immune</h3>
                <h4>Supercharge your immune system naturally!</h4>
                <div class="separator"></div>
                <ul>
                    <li><a href="/echinacea-plus.html">Echinacea Plus</a></li>
                    <li><a href="/super-c-plus-tablets.html">Super-C Plus</a></li>
                    <li><a href="/cold-flu-herbal-shot.html">Cold & Flu Herbal “SHOT”</a></li>
                    <li class="more-products"><a href="/immune.html">More Products</a></li>
                    
                    <!--<li><a href="/immune.html">Echinacea Plus</a></li>
                    <li><a href="/immune.html">Super-C Plus</a></li>
                    <li><a href="/immune.html">Cold & Flu Herbal “SHOT”</a></li>
                    <li class="more-products"><a href="/immune.html">More Products</a></li>-->
                </ul>
                <div class="img-container-outertube"><div class="img-container"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) ?>/wysiwyg/home/section1-1_article4.png" alt="Cold & Flu Herbal SHOT" /></div></div>
                <div class="view-all"><a class="blink1" href="/immune.html">VIEW ALL</a></div>
            </div>
        </article>
        <article class="article article3">
            <div class="inner-tube">
                <h3>Detox</h3>
                <h4>Cleanse and detoxify all of your elimination organs!</h4>
                <div class="separator"></div>
                <ul>
                    <li><a href="/5-day-bowel-detox.html">5-Day BOWEL Detox</a></li>
                    <li><a href="/5-day-liver-detox-program.html">5-Day LIVER Detox</a></li>
                    <li><a href="/5-day-kidney-detox-program.html">5-Day KIDNEY Detox</a></li>
                    <li class="more-products"><a href="/detox.html">More Products</a></li>
                    
                    <!--<li><a href="/detox.html">5-Day BOWEL Detox</a></li>
                    <li><a href="/detox.html">5-Day LIVER Detox</a></li>
                    <li><a href="/detox.html">5-Day KIDNEY Detox</a></li>
                    <li class="more-products"><a href="/detox.html">More Products</a></li>-->
                </ul>
                <div class="img-container-outertube"><div class="img-container"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) ?>/wysiwyg/home/section1-1_article3.png" alt="5-Day BOWEL Detox" /></div></div>
                <div class="view-all"><a class="blink1" href="/detox.html">VIEW ALL</a></div>
            </div>
        </article>
    </div>
</div>