<div class="content section1-3">
    <div class="table">
        <div class="table-row">
            <div class="table-cell">
                <div class="quote">
                    <p>I have made this year the easiest and simplest ever with my 5 Fundamental Product Categories to help you get your health back on track.<span class="small_quote">&rdquo;</span></p>
                    <span>Dr. Schulze</span>
                </div>
            </div>
            <div class="table-cell">
                <div class="img-container"><a href="/healthy-savings"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) ?>/wysiwyg/home/promo10.jpg" alt="Get Healthy Incentives. View Offers." /></a></div>
            </div>
        </div>
    </div>
</div>