<section class="section1 y">
    <div class="x w50 crusade-text">
        <h2 class="green">
            MY HEALTH CRUSADE
        </h2>
        <p class="w90">
            My personal commitment is to offer every American an OPTION to medical doctors, hospitals, surgery,
            chemical drugs and the physical, emotional and financial bankruptcy that this system of DISEASE
            MANAGEMENT causes. Unless maintaining chronic diseases with medical doctors, drugs and surgeries,
            and spending your nest egg to do it sounds like fun, I have an alternative. It's called health! In
            fact, I like to call it Creating Powerful Health! It's a lot more fun, less costly than managing
            disease, and lets you live life to your fullest potential. <br/>
            <br/>
            <span>—Dr. Schulze</span>
        </p>
    </div>

    <div class="x w50 crusade-image"></div>

    <div class="clear"></div>
</section>

<section class="section2 y">
    <div class="x w50 journey" id="my-personal-healing-journey">
        <div>
            <h2 class="green">
                MY PERSONAL <span>HEALING JOURNEY</span>
            </h2>
            <p>
                At the age of 16, after a year of ill health, young Richard Schulze was diagnosed with a genetic
                heart deformity. The doctors told him that without major heart surgery, he would be dead by twenty.
                Discover the amazing, powerful healing journey that  led Dr. Schulze to become one of the foremost
                Natural Healers and Master Herbalists on the planet.
            </p>
			<span>
				<a class="blink1" href="http://herbdocblog.com/dr-schulze-biography/">READ FULL BIO</a>
			</span>
        </div>
    </div>

    <div class="x w50 formula">
        <div>
            <h2 class="green">
                WHY MY FORMULAS <span>ARE THE BEST</span>
            </h2>
            <p>
                Nothing is more important to me than your health, and the health of your family and loved ones.
                This may sound cliché but I assure you...<br/>
                YOU are my mission.
            </p>
			<span>
				<a class="blink1" href="/herbalformuladifferent">READ MORE</a>
			</span>
        </div>
    </div>

    <div class="clear"></div>
</section>

<section id="drschulze-section3" class="section3 y">
    <h2 class="blog-header">
        VISIT <span>DR. SCHULZE'S</span> BLOG
    </h2>

    <div class="blog-items">
        <div class="x w50 blog-text">
            <div>
                <h3>
                    Dr. Schulze's Blog
                </h3>
                <p>The mission of my BLOG is to illuminate and empower you with so much Natural Healing and Herbal Medicine Wisdom, Specifics, Remedies, Quick Fixes, Programs, Tools and general Know How, that whenever you need it, you've got it. Every Wednesday, I post a new answer to one of your submitted questions or a new commentary on health and healing. And, I archive ALL of them, so you have an awesome LIBRARY of healing information right at your fingertips, anytime you need it. Plus, ALL of my BOOKS, CDs and DVDs are right on this site, too! You can READ any of my books, WATCH any of my DVDs or LISTEN to any of my CDs right on your computer, iPad or even your phone – anywhere you can get on the Internet!</p>
				<span>
					<a class="blink1" href="http://herbdocblog.com/">LEARN MORE</a>
				</span>
            </div>

        </div>

        <div class="x w50 blog-image"></div>
    </div>
    <div class="clear"></div>
</section>

<div class="splitter"></div>

<section class="section4 y">
    <h2 id="booksandmedia">
        SELECTED BOOKS &amp; <div>MEDIA</div>
    </h2>

    <div class="media-items">
        <div class="x media">
            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) ?>wysiwyg/cms/drschulze/dr-schulze-book1.png" alt="" title="" />
            <h3>
                KEEP CALM AND GET HEALTHY
            </h3>
            <p>
                This book explains why you don't have to panic and rush to make a costly, life-changing or even    
                life-threatening decision.
            </p>
			<span>
				<a class="blink1" href="/keep-calm-stay-healthy-book">Read More</a>
			</span>
        </div>

        <div class="x media">
            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) ?>wysiwyg/cms/drschulze/dr-schulze-book2.png" alt="" title="" />
            <h3>
                FIRST AID AT HOME CD
            </h3>
            <p>
                With his latest DVD, Dr. Schulze shows you ALL of his natural first aid routines for treating bangs,
                bumps and bruises! Treating burns!
            </p>
			<span>
				<a class="blink1 lightbox-vimeo" href="https://vimeo.com/107618621">Watch Video</a>
			</span>
        </div>

        <div class="x media">
            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) ?>wysiwyg/cms/drschulze/dr-schulze-book3.png" alt="" title="" />
            <h3>
                5-DAY DETOX
            </h3>
            <p>
                The real cause behind the majority of sickness and disease in America is the retention and storage
                of toxic, poisonous waste in our colon.
            </p>
			<span>
				<a class="blink1"  href="/5-day-bowel-detox-book">Read More</a>
			</span>
        </div>
    </div>
    <div class="clear"></div>
</section>