<div class="col-main-content">

    <section class="section1 clearfix">
        <div class="inner-tube">
            <h1> Herbal Formulae That Work!</h1>
            <h2>Dr. Schulze’s Original Clinical Formulae Since 1979</h2>
            <div class="table">
                <div class="table-row">
                    <div class="table-cell col1">
                        <div class="image-container">
                            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/cms/learn/formulae.jpg" />
                        </div>
                    </div>
                    <div class="table-cell col2">
                        <div class="content-container">
                            <h5>Dr. Schulze's Difference</h5>
                            <p>To understand my herbal formulas, you must first understand me. After all, it is my life, my personal healing experiences, my wonderful patients and my clinical experience that created my values, the values that are now the core principles of this company. It is important that you know what is important to me, so you know exactly what you are purchasing.</p>
                            <div id=real>
                            <a class="blink1 read-more" href="<?php echo $this->getUrl('difference'); ?>">Read More</a>
                            <!-- <a class="blink1 watch-video lightbox-vimeo" href="https://vimeo.com/105924445">Watch Video</a> -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="image-container">
                <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/cms/learn/formulae.jpg" />
               
            </div>
        </div>

    </section>

    <section class="section2 clearfix">
        <div class="column-left-container">
            <div class="column left">
                <div class="inner-tube">
                    <h3>How Our Products Work</h3>
                    <ul>
                        <li><a href="<?php echo $this->getUrl('common-dosage-questions-answers'); ?>">Common Dosage Question &amp; Answers</a></li>
                        <li><a href="<?php echo $this->getUrl('quick-start'); ?>">QuickStart Directions</a></li>
                        <li class="video">
                            <a class="lightbox-vimeo" href="https://vimeo.com/106951187">My Herbal Products &amp; How To Use Them</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="column right">
            <div class="inner-tube">
            	 
                <h3>Real People. Real Results.</h3>
            	 
                <ul>
	                 <li>
                        <h5>DEEP TISSUE</h5>
                        <p>I was given the Dr. Schulze’s Deep Tissue Ointment. I used it on my heel and massaged it, and immediately the pain was gone!</p>
                        <span>-R.Z., Inglewood, CA</span>
                    </li>

	             <li>
                        <h5>VARIOUS PRODUCTS</h5>
                        <p>I've been suffering obesity for 40 years, but my weight dropped when I was eating 2 SuperFood Crunch bars a day, doubling up my SuperFood Powder, taking Protect and Intestinal Formula#1. It's a miracle!</p>
                        <span>-N.R., Sarasota, FL</span>
                    </li>
	              <li>
                        <h5>VARIOUS PRODUCTS</h5>
                        <p>My father was sent to the cardiologist for a triple bypass. Doctor said to get cleaned up in six months. He did the Bowel Detox, he's taking the Heart Formula and Protect. After six months results, he does not need surgery.</p>
                        <span>-N.K., Westland, MI</span>
                    </li>
				 <li>
                        <h5>SUPERFOOD PLUS</h5>
                        <p>I had a gastric bypass surgery which threw off my entire digestive system. The only product that helps keep things normal is the SuperFood Plus Tablets!</p>
                        <span>-M.S., Anaheim, CA</span>
                    </li>
                    <li>
                        <h5>SUPERFOOD PLUS</h5>
                        <p>My cousin had really bad asthma. Her mom began giving her SuperFood mixed with organic apple juice every morning. Her asthma is now totally gone. She is now able to run track and she plays basketball!</p>
                        <span>-M.W., Hawthorne, CA</span>
                    </li>
	                <li>
                        <h5>INTESTINAL FORMULA #1</h5>
                        <p>Dr. Schulze's Intestinal Formula #1 is this girl’s secret weapon! Before, I was walking around bloated and feeling toxic and constantly lethargic. Now I feel clean and clear!</p>
                        <span>-A. A., Los Angeles, CA</span>
                    </li>
                    
                	<li>
                        <h5>SUPERFOOD PLUS</h5>
                        <p>I cannot go without SuperFood. It is my life source!</p>
                        <span>-Joe F., Ocala, FL</span>
                    </li>
                    <li>
                        <h5>CAYENNE</h5>
                        <p>My sinus congestion was instantly cured with your Cayenne! Thanks, Dr. Schulze!</p>
                        <span>-Ken G.</span>
                    </li>
                    <li>
                        <h5>SUPERFOOD PLUS</h5>
                        <p>My 97-year-old mother takes SuperFood religiously, and it is why she's alive today. She has a lot of energy and is getting great nutrition!</p>
                        <span>-Carolyn R., Cheyenne, WA</span>
                    </li>
                    <li>
                        <h5>PROSTATE</h5>
                        <p>In less than 24 hours of use, I slept for 7 hours without urgently having to urinate. Normally I go 2-3 times a night. Thank you.</p>
                        <span>-Ralph R. in NY</span>
                    </li>
                    <li>
                        <h5>COLD & FLU HERBAL SHOT</h5>
                        <p>I never get sick anymore because I take a SHOT every time I feel a flu-like symptom coming on.</p>
                        <span>-E.S., Fairfield, CA</span>
                    </li>
                    
                     <li>
                        <h5>INTESTINAL FORMULA #2</h5>
                        <p>I love this product! It saved my life! I tried other products and nothing else worked they way #2 does. I believe in always keeping the colon clear so I don’t get sick.</p>
                        <span>-C.S., Santa Rosa Beach, FL</span>
                    </li>
                    
                     <li>
                        <h5>VARIOUS PRODUCTS</h5>
                        <p>4 years ago I was diagnosed with Hepatitis C. I took your liver/gallbladder L-GB formula, your Echinacea Plus, your SuperFoods, and to top all of that off I did your liver cleanse, these things saved my life.</p>
                        <span>-S.S., Santa Fe, NM</span>
                    </li>

                    
                    <li>
                        <h5>5-DAY BOWEL DETOX</h5>
                        <p>I am 49 years old. I have been sick for over 10 years and tried your 5-Day BOWEL Detox and felt great. Felt like I was 20 again. I need to continue to do these detoxes every quarter. Loved, loved, loved your product.</p>
                        <span>- Chris B. in Clayton, DE</span>
                    </li>
                    <li>
                        <h5>PROTECT & SUPERFOOD</h5>
                        <p>I have always had trouble getting started in the morning, but since I started taking Dr. Schulze Protect Formula, two tablets along with my 5 SuperFood tablets or powder and I feel sharp and ready to face the day.</p>
                        <span>- Todd M., Al Hambra, CA</span>
                    </li>
                    <li>
                        <h5>VARIOUS PRODUCTS</h5>
                        <p>I started using your products in October. I stopped eating meat, detoxed and lost 20 pounds. I feel great! Thank you, Dr. Schulze!</p>
                        <span>- Fritz M., Long Beach, CA</span>
                    </li>
                    <li>
                        <h5>INTESTINAL FORMULA #1</h5>
                        <p>Your Intestinal Formula #1 works great! It works wonderfully and I think it is the most effective formula on earth! Thank you.</p>
                        <span>- T.G., San Pedro, CA</span>
                    </li>
                    <li>
                        <h5>HERBALMUCIL PLUS</h5>
                        <p>I have used HerbalMucil Plus for almost one month. Immediately, I felt relief in my bowel system from constipation and bloating and a general feeling of wellness. Another great product!</p>
                        <span>- Laura B., Agoura Hills, CA</span>
                    </li>
                    <li>
                        <h5>ECHINACEA PLUS</h5>
                        <p>Your Echinacea Plus keeps me from missing days from work and away from my family. That’s a good thing in my life. Your products are the best!!</p>
                        <span>- Renolado M.</span>
                    </li>
                    <li>
                        <h5>BOWEL SHOT</h5>
                        <p>Your Bowel SHOT is very helpful to have for those times we “overdo it” with bad food. It gets the bad stuff out.</p>
                        <span>- Delores M., Los Angeles, CA</span>
                    </li>
                    <li>
                        <h5>24-HOUR BOWEL DETOX</h5>
                        <p>As a safari guide, I take several 24-hour Bowel Detox packets with me. When a client gets sick with diarrhea, I give them the 24-hour packet to clean out and get back to safari.</p>
                        <span>- Christopher L.</span>
                    </li>
                    <li>
                        <h5>DIGESTIVE SHOT</h5>
                        <p>The Digestive SHOTS really work. Very helpful after a bad meal. I’ve tried it several times and it’s GREAT!</p>
                        <span>- Alex W., Los Angeles, CA</span>
                    </li>
                    <li>
                        <h5>ECHINACEA PLUS</h5>
                        <p>Your Echinacea Plus has always stopped my cold and flu symptoms whenever I start getting sick. It has been a great help to me and my family. Many thanks!</p>
                        <span>- Hector R.</span>
                    </li>
                    <li>
                        <h5>MALE SHOT</h5>
                        <p>Dude, that Male Shot is some powerful stuff. I have been on it for three days. After the second day, my wife asked me what I was on? She is even more pleased and pleasured.</p>
                        <span>- Damien B., Largo, MD</span>
                    </li>
                    <li>
                        <h5>DETOX TEA</h5>
                        <p>I have been drinking the Detox Tea to cleanse my liver and have never felt better. I have lots of energy, my skin is clear and I have lost 6 pounds. I would recommend your products very highly.</p>
                        <span>- E.W., Playa Vista, CA</span>
                    </li>
                    <li>
                        <h5>INTESTINAL FORMULA #1</h5>
                        <p>Thank you for providing me with a true miracle! I have suffered with severe constipation for most of my life and had found nothing, which offered me both total relief and ultimate healing power.</p>
                        <span>- Jackie C.</span>
                    </li>
                    <li>
                        <h5>5-DAY BOWEL DETOX</h5>
                        <p>I feel great, sleep better, and lost about 17 pounds. The 5-Day BOWEL Detox really works!</p>
                        <span>- Norman C., Los Angeles, CA</span>
                    </li>
                    <li>
                        <h5>FEMALE BALANCE</h5>
                        <p>The results are fabulous. No cramps. My family gets saved, especially my husband. And most importantly I feel good! Once I take the Female Balance, all I know is that this wave of calmness passes over my body.</p>
                        <span>- Madeline L.</span>
                    </li>
                    <li>
                        <h5>SUPER GINSENG</h5>
                        <p>I was very tired and thanks to your special Super Ginseng Blend, I have energy like when I was 21. God bless Dr. Schulze!</p>
                        <span>- R.R.</span>
                    </li>
                    <li>
                        <h5>NERVE</h5>
                        <p>I have had problems sleeping for many years and have tried various prescription medications, but this one has no side effects and I can now sleep through the entire night. Thanks, Dr. Schulze!</p>
                        <span>- Keith W.</span>
                    </li>
                    <li>
                        <h5>TOOTH & GUM</h5>
                        <p>I had bleeding gums, but now I’m juicing and using your Tooth & Gum, my dentist is amazed! My gums are now very strong. Thanks.</p>
                        <span>- F.T., San Jose, CA</span>
                    </li>
                    <li>
                        <h5>EYEBRIGHT</h5>
                        <p>I started using your Eyebright three months ago. Now I only need to wear my glasses when I write a check!</p>
                        <span>- E.G., Gardena, CA</span>
                    </li>
                    <li>
                        <h5>DEEP TISSUE</h5>
                        <p>I use the Deep Tissue on any bruises I get, and any my 2-year-old gets. Little kids like to fall a lot and I have watched a bruise disappear in 24 hours. It goes from dark purple to yellow to gone in less than a day!</p>
                        <span>- L.G., Santa Monica, CA</span>
                    </li>
                    <li>
                        <h5>JOJOBA & TEA TREE OIL</h5>
                        <p>I use your Jojoba & Tea Tree after I shave. It’s the only product that does not irritate my very sensitive skin. I love it!</p>
                        <span>- M.F., Marina del Rey, CA</span>
                    </li>
                    <li>
                        <h5>SUPERTONIC</h5>
                        <p>I would get the flu or a bad cold every December and lose work, sometimes for a whole week. Then I tried your SuperTonic and haven’t had a cold or flu since! Now all my friends and kids use it and love it.</p>
                        <span>- P.S., Davison, MI</span>
                    </li>
                    <li>
                        <h5>AIR DETOX</h5>
                        <p>I love your Air Detox! I take it with me whenever I travel. I start by spraying the intake air screens in the hotel and it immediately sends a fresh smell throughout the room. It’s great!</p>
                        <span>- Tricia H.</span>
                    </li>
                    <li>
                        <h5>SUPER-C</h5>
                        <p>I have been using the Super-C powder for nine months now and notice my skin is a lot smoother!</p>
                        <span>L.L., Mt. Vernon, NY</span>
                    </li>
                    <li>
                        <h5>AIR DETOX</h5>
                        <p>Air Detox spray has helped my living space stay fresh!</p>
                        <span>M.V., Long Beach, CA</span>
                    </li>
                    <li>
                        <h5>SUPERFOOD PLUS</h5>
                        <p>I had hair loss due to chemo. After my chemo treatment was done I was still losing hair, but I started using SuperFood Plus and my hair started to grow back!</p>
                        <span>Debbie R., Kutztown, PA</span>
                    </li>

					 <li>
                        <h5>DAILY ORAL THERAPY, TOOTH & GUM FORMULA</h5>
                        <p>I completely cured a tooth abscess using Daily Oral Therapy and Tooth & Gum Formula.</p>
                        <span>-M.G., Marina del Rey, CA</span>
                    </li>

                </ul>
                <div class="buttons-set">
                    <a class="blink1" onclick="ga('send', 'event', 'Learn Page Carousel', 'SHARE YOUR STORY', 'Testimonials');" href="<?php echo $this->getUrl('submit-your-natural-healing-story'); ?>">Share Your Story</a>
                </div>
            </div>
        </div>
    </section>

    <section class="section3 clearfix">
        <div class="table">
            <div class="table-row">
                <div class="table-cell col1">
                    <div class="content-container">
                        <h3>The Power Of Natural Healing</h3>
                        <h4>Dr. Schulze's Natural Approach to TRUE Health &amp; Healing</h4>
                        <?php /* Remove but source control for safety rollback.
                        <div class="compare">
                            <p>Health Care</p>
                            <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Vs.</p>
                            <p>Disease Care</p>
                        </div>
                        */ ?>
                        <p>
                            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/cms/learn/power-natural-healing.png" />
                            I’m Dr. Richard Schulze, and over the past 40 years, thousands of people have asked me the same question: What exactly is Natural Healing and how does it work?  So I’d like to take a few minutes to give you some of my insights and understanding of Natural Healing.  From spending decades in the clinic with thousands of patients, I found that it’s important for everyone to understand the basics of how and why your body will heal you of any disease and help you to create powerful health.
                        </p>
                        <a class="blink1" href="<?php echo $this->getUrl('about-natural-healing'); ?>">Read More</a>
                    </div>
                </div>
                <div class="table-cell col2">
                    <div class="image-container">
                        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/cms/learn/power-natural-healing.png" />
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="section4 clearfix">
        <div class="content-container">
            <h3>Common Sense Wisdom from Dr. Schulze</h3>
            <h4>Dr. Schulze's Books, Audio, Video &amp; more!</h4>
        </div>
    </section>

    <section class="section5 clearfix">
        <div class="table">
            <div class="table-row">
                <div class="table-cell col1 clearfix">
                    <div class="table-container">
                        <h4>20 Steps<br />To A Healthier Life</h4>
                        <div class="column-left-container">
                            <div class="column left">
                                <div class="image-container">
                                    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/cms/learn/book1.jpg" />
                                </div>
                            </div>
                        </div>
                        <div class="column right">
                            <div class="inner-tube">
                                <h4>20 Steps<br />To A Healthier Life</h4>
                                <p>
                                    Read the book that has changed countless lives, and put them on the path to Create Powerful Health Naturally!
                                    <span><a href="/20-powerful-steps">View</a> or <a target="_blank" href="/media/wysiwyg/pdf/20-Steps.pdf">Download</a></span>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="table-cell col2 clearfix">
                    <div class="table-container">
                        <h4>Dr. Schulze's<br />Official Blog Site</h4>
                        <div class="column-left-container">
                            <div class="column left">
                                <div class="image-container">
                                    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/cms/learn/book2.jpg" />
                                </div>
                            </div>
                        </div>
                        <div class="column right">
                            <div class="inner-tube">
                                <h4>Dr. Schulze's<br />Official Blog Site</h4>
                                <p>
                                    Get weekly videos from Dr. Schulze -answering questions, sharing his wisdom, and empowering you to heal yourself NATURALLY!
                                    <span><a href="/blog">Go To Blog Site</a></span>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="table-cell col3 clearfix">
                    <div class="table-container">
                        <h4>Herbal Products<br />Catalog</h4>

                        <div class="column-left-container">
                            <div class="column left">
                                <div class="image-container">
                                    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/cms/learn/2017-Catalog.jpg" />
                                </div>
                            </div>
                        </div>
                        <div class="column right">
                            <div class="inner-tube">
                                <h4>Herbal Products<br />Catalog</h4>
                                <p>
                                    Discover Dr. Schulze's entire line of original clinical herbal formulae!
                                   <span><a href="latest-publication">View</a> or <a target="_blank" href="/media/wysiwyg/pdf/2017-Catalog-WEB.pdf">Download</a></span>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="section6 clearfix">
        <div class="content-container">
            <h3>Free Education At Your Doorstep!</h3>
            <p>Dr. Schulze will send you his powerful health and healing wisdom, and his over 30 years of common sense Natural Healing experience—for FREE!</p>
            <a class="blink1" href="<?php echo $this->getUrl('free-offers'); ?>">Get Free Offers</a>
            <div class="image-container">
                <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/cms/learn/free-offer-new.jpg" />
            </div>
        </div>
    </section>

</div>