<div class="video-wrapper" itemscope itemtype="http://schema.org/VideoObject">
    <div class="video">

        <div class="video-header">
            <img alt="100% Quality Guarantee" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) ?>wysiwyg/cms/store/guarantee.png" />
            <h2>REAL PEOPLE, <span>REAL RESULTS</span></h2>
            <p>Customers Share the Amazing Results of Using <span>Dr. Schulze's Herbal Products and Programs</span></p>
            <div class="clear"></div>
        </div>

        <div class="video-player">
            <img alt="Video Player" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) ?>wysiwyg/cms/store/player.png" />
        </div>

        <ul>
            <li data-video-id="107613589">
                <div class="video-thumb">
                    <img alt="Play Video" itemprop="thumbnail" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) ?>wysiwyg/cms/store/shannon.png" />
                </div>
                <div class="video-content">
                    <div class="video-title" itemprop="name">Shannon</div>
                    <div class="video-summary" itemprop="description">customer 13 years</div>
                    <!--<div class="video-date">July 17, 2013</div>-->
                </div>
                <div class="clear"></div>
            </li>
            <li data-video-id="107613588">
                <div class="video-thumb">
                    <img alt="Play Video" itemprop="thumbnail" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) ?>wysiwyg/cms/store/ann.png" />
                </div>
                <div class="video-content">
                    <div class="video-title" itemprop="name">Ann</div>
                    <div class="video-summary" itemprop="description">customer 4 years</div>
                    <!--<div class="video-date">July 17, 2013</div>-->
                </div>
                <div class="clear"></div>
            </li>
            <li data-video-id="107613587">
                <div class="video-thumb">
                    <img alt="Play Video" itemprop="thumbnail" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) ?>wysiwyg/cms/store/andrea.png" />
                </div>
                <div class="video-content">
                    <div class="video-title" itemprop="name">Andrea</div>
                    <div class="video-summary" itemprop="description">customer 2 years</div>
                    <!--<div class="video-date">July 17, 2013</div>-->
                </div>
                <div class="clear"></div>
            </li>
        </ul>
        <div class="clear"></div>
    </div>
</div>
