<?php
/*
 * Author: Aydus
 * Description:
 *  - Custom header.
 */
?>
<div class="hidden-all show-mobile seals">
	<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_seals')->toHtml(); ?>
</div>
<div class="outer">
	<div class="menu">
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_links1')->toHtml(); ?>
	</div>
	<div class="shortcuts">
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_links2')->toHtml(); ?>
	</div>
</div>
<div class="copyright-top">
	<p>These statements have not been evaluated by the Food and Drug Administration. These products are not intended to diagnose, treat, cure, or prevent any disease. Consult your doctor before taking any of these products.<br>*When available, free shipping offers apply to domestic orders only.</p>
</div>