<div class="col-main-content">
	<section class="section1 clearfix">
        <div class="inner-tube">
            <h1>START YOUR DETOX PROGRAM!</h1>
            <!-- <h2>Original Clinical Formulae Since 1979</h2> -->
            <div class="table">
            <div class="table-row">
                <div class="table-cell col1 clearfix">
                    <div class="table-container">
                        <div class="column-left-container">
                            <div class="column left">
                                <div class="image-container">
                                    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/cms/quickstart/5-Day-Bowel-quickstart.jpg" />
                                </div>
                            </div>
                        </div>
                        <div class="column right">
                            <div class="inner-tube">
                                <p>
									<span><a class="blink1" target="_blank" href="/media/wysiwyg/pdf/5-Day-Bowel-Detox_quickstart.pdf">View &amp; Print</a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="table-cell col2 clearfix">
                    <div class="table-container">
                        <div class="column-left-container">
                            <div class="column left">
                                <div class="image-container">
                                    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/cms/quickstart/5-Day-Liver-quickstart.jpg" />
                                </div>
                            </div>
                        </div>
                        <div class="column right">
                            <div class="inner-tube">
                                <p>
									<span><a class="blink1" target="_blank" href="/media/wysiwyg/pdf/5-Day-Liver-Detox_quickstart.pdf">View &amp; Print</a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="table-cell col3 clearfix">
                    <div class="table-container">
                        <div class="column-left-container">
                            <div class="column left">
                                <div class="image-container">
                                    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/cms/quickstart/5-Day-Kidney-quickstart.jpg" />
                                </div>
                            </div>
                        </div>
                        <div class="column right">
                            <div class="inner-tube">
                               <p>
								   <span><a class="blink1" target="_blank" href="/media/wysiwyg/pdf/5-Day-Kidney-Detox_quickstart.pdf">View &amp; Print</a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
				<div class="table-cell col4 clearfix">
                    <div class="table-container">
                        <div class="column-left-container">
                            <div class="column left">
                                <div class="image-container">
                                    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/cms/quickstart/30-Day-Detox-quickstart.jpg" />
                                </div>
                            </div>
                        </div>
                        <div class="column right">
                            <div class="inner-tube">
                                 <p>
									 <span><a class="blink1" target="_blank" href="/media/wysiwyg/pdf/30-Day-Detox_quickstart.pdf">View &amp; Print</a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>