
<!--Section Banner 1-->
<h2 style="color: #333333; font-size: 36px; text-align: center; padding-top:80px;">You have just taken an important step in your journey to <span style="color:#AA0803;"> HEALTH</span> and <span style="color:#AA0803;">VITALITY.</span></h2>
<section class="section1 clearfix">
	<div class="media-items" style="text-align: -moz-center; padding-bottom:10px;">
                    <img style="display: block; margin-left: auto; margin-right: auto; " src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/cms/landingpages/freeshipping.jpg" />
    </div>
</section>

<!-- Section 1-->
<section class="section3 clearfix">
    <div class="column-middle-container">
        <div class="column middle">
            <div class="inner-tube">
               
                 <div class="table" style="margin-left: -10%; width: 101%;">
                <div class="table-row head">
                    <div class="table-cell" align="middle" style="background-color: #154020; color: #ffffff;">Great Deal </div>
                   
                </div>
                
                 <div class="table-row">
                    <div class="table-cell"  style="padding-left: 14px; padding-top: 27px; padding-bottom: 41px; background-color: #c5e0eb;">Buy 2 jars of SuperFood Plus & <br><span style="color:#AA0803;">Get a 3rd jar FREE!</span><br>FREE shipping  & FREE CD!</div>
                    
                </div>
                
           </div>

            </div>
        </div>
    </div>

    <div class="column left" style="margin-top: -2.7%;">
        <div class="inner-tube">
            
            <div class="table" style="margin-left: -13%; width: 100%;">
                <div class="table-row head">
                    <div class="table-cell" align="middle">Best Deal </div>
                   
                </div>
                
                 <div class="table-row">
                    <div class="table-cell" style="padding-bottom: 25px; padding-left: 20px; padding-top: 20px;">Home Delivery Program<br> <span style="color:#AA0803;"> Get your 4th and 5th months FREE!</span><br> FREE to join! Cancel at any time!<br> FREE shipping every month!</div>
                    
                </div>
                
           </div>
      </div>
    </div>

    <div class="column right">
        <div class="inner-tube">
                  <div class="table" style="width: 97%; margin-left:-7%;">
                <div class="table-row head">
                    <div class="table-cell" align="middle" style="background-color: #154020; color: #ffffff;">Trial Deal </div>
                   
                </div>
                
                 <div class="table-row">
                    <div class="table-cell" style="padding-left: 14px; padding-top: 26px; padding-bottom: 65px; background-color: #cfebc5;"><span style="color:#AA0803;">Save 20% on Superfood Plus </span><br>FREE shipping  & Free CD</div>
                    
                </div>
                
           </div>
            
        </div>
    </div>
</section>




