<div class="blog content-page">
	<div class="section1 col1">
		<div class="navigation"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/cms/blog/nav.jpg" /></div>
	</div>
	</div>
	<div class="section2 col2">
		<div class="column1">
		<p><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/cms/blog/22-ABP-Blog-Landing-4_02.jpg" width="248" height="48" alt="">
		<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/cms/blog/22-ABP-Blog-Landing-4_05.jpg" width="248" height="66" alt="">
		<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/cms/blog/22-ABP-Blog-Landing-4_07.jpg" width="248" height="222" alt="">
		<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/cms/blog/22-ABP-Blog-Landing-4_14.jpg" width="248" height="154" alt="">
		<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/cms/blog/22-ABP-Blog-Landing-4_17.jpg" width="248" height="262" alt="">
		<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/cms/blog/22-ABP-Blog-Landing-4_24.jpg" width="248" height="86" alt="">
		<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/cms/blog/22-ABP-Blog-Landing-4_28.jpg" width="248" height="320" alt="">
	</div>
	<div class="column2">
		<div class="post-section">
			<div class="post-image"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/cms/blog/22-ABP-Blog-Landing-4_03.jpg" alt=""></div>
			<div class="post-header"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/cms/blog/22-ABP-Blog-Landing-4_04.jpg" alt=""></div>
			<div class="post-summary"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/cms/blog/22-ABP-Blog-Landing-4_13.jpg" alt=""></div>
			<div class="post-link"><a class="blink1 read-more" href="http://herbdoc-production.aydus.com/difference/">Read More</a></div>
			<div class="clear"></div>
			<div class="post-divider"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/cms/blog/22-ABP-Blog-Landing-4_10.jpg" width="940" height="22" alt=""></div>
		</div>
		<div class="post-section">
			<div class="post-image"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/cms/blog/22-ABP-Blog-Landing-4_11.jpg" alt=""></div>
			<div class="post-header"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/cms/blog/22-ABP-Blog-Landing-4_04.jpg" alt=""></div>
			<div class="post-summary"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/cms/blog/22-ABP-Blog-Landing-4_13.jpg" alt=""></div>
			<div class="post-link"><a class="blink1 read-more" href="http://herbdoc-production.aydus.com/difference/">Read More</a></div>
			<div class="clear"></div>
			<div class="post-divider"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/cms/blog/22-ABP-Blog-Landing-4_10.jpg" width="940" height="22" alt=""></div>
		</div>
		<div class="post-section">
			<div class="post-image"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/cms/blog/22-ABP-Blog-Landing-4_19.jpg" alt=""></div>
			<div class="post-header"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/cms/blog/22-ABP-Blog-Landing-4_04.jpg" alt=""></div>
			<div class="post-summary"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/cms/blog/22-ABP-Blog-Landing-4_13.jpg" alt=""></div>
			<div class="post-link"><a class="blink1 read-more" href="http://herbdoc-production.aydus.com/difference/">Read More</a></div>
			<div class="clear"></div>
			<div class="post-divider"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/cms/blog/22-ABP-Blog-Landing-4_10.jpg" width="940" height="22" alt=""></div>
		</div>
		<div class="post-section">
			<div class="post-image"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/cms/blog/22-ABP-Blog-Landing-4_26.jpg" alt=""></div>
			<div class="post-header"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/cms/blog/22-ABP-Blog-Landing-4_04.jpg" alt=""></div>
			<div class="post-summary"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/cms/blog/22-ABP-Blog-Landing-4_13.jpg" alt=""></div>
			<div class="post-link"><a class="blink1 read-more" href="http://herbdoc-production.aydus.com/difference/">Read More</a></div>
			<div class="clear"></div>
			<div class="post-divider"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/cms/blog/22-ABP-Blog-Landing-4_10.jpg" width="940" height="22" alt=""></div>
		</div>
	</div>
</div>