<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<div class="blog-home">
    <?php $posts = $this->getPosts(); ?>
    <?php if (count($posts) > 0): ?>
        <div class="post-list">
            <ul id="post-list">
                <?php foreach ($posts as $post): ?>
                <li class="item">
                    <div class="post-list-item">
                        <?php if ($post): ?>
                            <?php $helper = $this->helper('wordpress') ?>
                            <?php $author = $post->getAuthor() ?>
                            <div class="blog-desc">
                                <?php /* if ($featuredImage = $post->getFeaturedImage()): ?>
                                    <div class="featured-image post-book">
                                        <a href="<?php echo Mage::getBaseUrl() .'blog/book/'.$post->getPostName() ?>" title="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"><img src="<?php echo $featuredImage->getAvailableImage() ?>" alt="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"/></a>
                                    </div>
                                <?php endif; */ ?>
                                <h2><a href="<?php echo Mage::getBaseUrl() .'blog/book/'.$post->getPostName() ?>" title="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"><?php echo $this->escapeHtml($post->getPostTitle()) ?></a> </h2>
                                <?php echo $this->getBeforePostContentHtml() ?>
                                <!--<p class="post-meta details"><?php echo $post->getPostDate() . ", " . $post->getPostType(); ?><span class="by-author"> by <?php echo $post->getAuthor()->getDisplayName(); ?></span></p>-->
                                <div class="post-entry entry">
                                    <?php if ($post->isViewableForVisitor()): ?>
                                        <?php if ( $post->hasMoreTag()): ?>
                                            <?php echo $post->getPostExcerpt() ?>
                                        <?php else: ?>
                                            <?php echo $post->getPostContent(); ?>
                                        <?php endif; ?>
                                    <?php else: ?>
                                        <?php echo $this->getPasswordProtectHtml($post) ?>
                                    <?php endif; ?>
                                </div>                 
                                <div class="post_readmore_btn"><a href="<?php echo Mage::getBaseUrl() .'blog/book/'.$post->getPostName()  ?>" title="<?php echo $this->escapeHtml($post->getPostTitle()) ?>">Click to Read</a></div>
                            </div>
                        <?php endif; ?>
                    </div>
                    </li>
                <?php endforeach; ?>
            </ul>
<!--            <script type="text/javascript">decorateList($('post-list'));</script>-->
            <?php //echo $this->getPagerHtml() ?>
        </div>
    </div>
<?php endif; ?>