<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<div class="blog-home">
    <?php $posts = $this->getPosts(); ?>
    <?php if (count($posts) > 0): ?>
        <div class="post-list video">
            <ul id="post-list">
                <?php foreach ($posts as $post): ?>
                <li class="item">
                    <div class="post-list-item">
                        <?php if ($post): ?>
                            <?php $helper = $this->helper('wordpress') ?>
                            <?php $author = $post->getAuthor(); ?>
                            <div class="blog-desc">
                                 <h2><a href="<?php echo Mage::getBaseUrl() .'blog/video/'.$post->getPostName() ?>" title="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"><?php echo $this->escapeHtml($post->getPostTitle()) ?></a> </h2>
                                <?php echo $this->getBeforePostContentHtml() ?>
                                <p class="post-meta details"><?php echo $post->getPostDate() . ", " . $post->getPostType(); ?><span class="by-author"> by <?php echo $post->getAuthor()->getDisplayName(); ?></span></p>
                                     <?php $imgnm = explode(';', $post->getMetaValue('mf_post_video')); ?>
                                <?php if ($imgnm[0] != "") { $featuredImage = Mage::getBaseUrl() . "wp/images/video/" . $imgnm[0] . ".jpg"; } else { if($featuredImage11 = $post->getFeaturedImage()){ $featuredImage = $featuredImage11->getAvailableImage(); } } ?>
                                <?php if($featuredImage != ""){ ?>
                                    <div class="featured-image">
                                        <a href="<?php echo Mage::getBaseUrl() .'blog/video/'.$post->getPostName() ?>" title="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"><img src="<?php echo $featuredImage; ?>" alt="<?php echo $this->escapeHtml($post->getPostTitle()) ?>" /></a>
                                    </div>
                                <?php } ?>
                               
                                
                                <div class="post-entry entry">
                                    <?php if ($post->isViewableForVisitor()): ?>
                                        <?php if ( $post->hasMoreTag()): ?>
                                            <?php echo $post->getPostExcerpt() ?>
                                        <?php else: ?>
                                            <?php echo $post->getPostContent(); ?>
                                        <?php endif; ?>
                                    <?php else: ?>
                                        <?php echo $this->getPasswordProtectHtml($post) ?>
                                    <?php endif; ?>
                                </div>                 
                                <div class="post_readmore_btn"><a href="<?php echo Mage::getBaseUrl() .'blog/video/'.$post->getPostName() ?>" title="<?php echo $this->escapeHtml($post->getPostTitle()) ?>">CLICK TO VIEW</a></div>
                            </div>
                        <?php endif; ?>
                    </div>
                    </li>
                <?php endforeach; ?>
            </ul>
<!--            <script type="text/javascript">decorateList($('post-list'));</script>-->
            <?php //echo $this->getPagerHtml() ?>
        </div>
    </div>
<?php endif; ?>