<?php //$_helper    = $this->helper('catalog/output'); ?>
<?php //$_category  = $this->getCurrentCategory(); ?>

<div class="banner-container">
    <div class="container">
        <span><?php echo ($this->getHeaderText() || $this->getHeaderText() === false) ? $this->getHeaderText() : $this->__("Search results for '%s'", $this->helper('catalogsearch')->getEscapedQueryText()) ?></span>
    </div>
</div>