<div class="header" style="background: white;display: inline-block;min-height: 139px; width: 630px;">
	<div class="logo" style="width: 257px; display: inline-block;float:left;">
		<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/email/logo.png" />
	</div>
	<div style="width: 370px; display: inline-block;float:left;">
		<div class="phone-number" style="height: 36px; width: 387px; background: #d8d1c3; text-align: center;display: inline-block;">
					<a href="tel:18004372362"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/email/phone.png" /></a>
		</div>
		<div class="menu" style="width: 385px;">
			<ul style="list-style: none;margin: 20px 0 0 20px;padding: 0; text-align: center;">
				<li style="padding: 0 25px; width:50px; float:left;"><a href="http://herbdoc-production.aydus.com/store"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/email/shop.png" /></a></li>
				<li style="padding: 0 25px; width:50px; float:left;"><a href="http://herbdoc-production.aydus.com/learn"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/email/learn.png" /></a></li>
				<li style="padding: 0 25px; width:50px; float:left;"><a href="http://herbdoc-production.aydus.com/dr-schulze"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/email/dr-schulze.png" /></a></li>
			</tr>
		</div>
	</div>
</div>