
<!--Section Banner 1-->
<h2 style="color: #333333; font-size: 36px; text-align: center; padding-top:80px;">You have just taken an important step in your journey to <span style="color:#AA0803;"> HEALTH</span> and <span style="color:#AA0803;">VITALITY.</span></h2>
<section class="section1 clearfix">
	<div class="media-items" style="text-align: -moz-center; padding-bottom:10px;">
                    <img style="display: block; margin-left: auto; margin-right: auto; " src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/cms/landingpages/freeshipping.jpg" />
    </div>
</section>

<!-- Section 1-->
<section class="section3 clearfix">
    <div class="column-middle-container">
        <div class="column middle">
            <div class="inner-tube">
               
                 <div class="table">
                <div class="table-row head">
                    <div class="table-cell" align="middle" style="background-color: #154020; color: #ffffff;">Great Deal </div>
                   
                </div>
                
                 <div class="table-row">
                    <div class="table-cell"  style="padding-left: 14px; padding-top: 27px; padding-bottom: 41px; background-color: #c5e0eb;">Buy 2 jars of SuperFood Plus & <br><span style="color:#AA0803;">Get a 3rd jar FREE!</span><br>FREE shipping  & FREE CD!</div>
                    
                </div>
                
           </div>

            </div>
        </div>
    </div>

    <div class="column left" style="margin-top: -2.7%;">
        <div class="inner-tube">
            
            <div class="table">
                <div class="table-row head">
                    <div class="table-cell" align="middle">Best Deal </div>
                   
                </div>
                
                 <div class="table-row">
                    <div class="table-cell" style="padding-bottom: 25px; padding-left: 20px; padding-top: 20px;">Home Delivery Program<br> <span style="color:#AA0803;"> Get your 4th and 5th months FREE!</span><br> FREE to join! Cancel at any time!<br> FREE shipping every month!</div>
                    
                </div>
                
           </div>
      </div>
    </div>

    <div class="column right">
        <div class="inner-tube">
                  <div class="table" style="width: 94%;">
                <div class="table-row head">
                    <div class="table-cell" align="middle" style="background-color: #154020; color: #ffffff;">Trial Deal </div>
                   
                </div>
                
                 <div class="table-row">
                    <div class="table-cell" style="padding-left: 14px; padding-top: 26px; padding-bottom: 65px; background-color: #cfebc5;"><span style="color:#AA0803;">Save 20% on Superfood Plus </span><br>FREE shipping  & Free CD</div>
                    
                </div>
                
           </div>
            
        </div>
    </div>
</section>




<!-- Section 2 Products-->

<section class="section2 clearfix">
<div class="col-main">
	<div class="category-products">
            <ul style="margin-left: -3%; width: 106%;" class="products-grid products-grid--max-4-col first last odd">
				<li class="item last">
					
						<a class="product-image" title="SuperFood Plus" href="https://www.herbdoc.com/superfood-plus-powder.html">
						<img style="float:left;" alt="SuperFood Plus" src="https://www.herbdoc.com/media/catalog/product/cache/1/small_image/210x/c96a280f94e22e3ee3823dd0a1a87606/s/u/superfood-powder_570_2.jpg" id="product-collection-image-572"></a><h2 class="product-name"><a title="SuperFood Plus" href="https://www.herbdoc.com/superfood-plus-powder.html">SuperFood Plus Powder</a></h2>
               
                <div class="product-info" style="min-height: 219px;">
                   
					<div class="size">14-ounce powder / 5-month supply</div> <br>                   
					<div class="price-box">
						<span id="product-price-572" class="regular-price">                            
						<span class="price">ONLY  $120.00</span>
						</span>
						<p class="saving">
                        	<span class="price-label"><span style="color:#AA0803; font-weight:bold;">Save $80.00</span></span>
                        </p>

					</div>

					<div class="actions">
						<button onclick="setLocation('https://www.herbdoc.com/checkout/cart/add/uenc/aHR0cHM6Ly93d3cuaGVyYmRvYy5jb20vZm91bmRhdGlvbmFsL251dHJpdGlvbmFsLmh0bWw,/product/572/form_key/P9dURYwtdEBCizZJ/')" class="button btn-cart" title="Add to Cart" type="button"><span><span>ORDER NOW</span></span></button>
					</div>
                </div>
            </li>
            <li class="item last">
					
						<a class="product-image" title="SuperFood Plus" href="https://www.herbdoc.com/superfood-plus-powder.html">
						<img style="float:left;" alt="SuperFood Plus" src="https://www.herbdoc.com/media/catalog/product/cache/1/small_image/210x/c96a280f94e22e3ee3823dd0a1a87606/s/u/superfood-powder_570_2.jpg" id="product-collection-image-572"></a><h2 class="product-name"><a title="SuperFood Plus" href="https://www.herbdoc.com/superfood-plus-powder.html">SuperFood Plus Powder</a></h2>
               
                <div class="product-info" style="min-height: 219px;">
                   
					<div class="size">14-ounce powder / 3-month supply</div> <br>                   
					<div class="price-box">
						<span id="product-price-572" class="regular-price">                            
						<span class="price">ONLY  $80.00</span>
						</span>
						<p class="saving">
                        	<span class="price-label"><span style="color:#AA0803; font-weight:bold;">Save $40.00</span></span>
                        </p>

					</div>

					<div class="actions">
						<button onclick="setLocation('https://www.herbdoc.com/checkout/cart/add/uenc/aHR0cHM6Ly93d3cuaGVyYmRvYy5jb20vZm91bmRhdGlvbmFsL251dHJpdGlvbmFsLmh0bWw,/product/572/form_key/P9dURYwtdEBCizZJ/')" class="button btn-cart" title="Add to Cart" type="button"><span><span>ADD TO CART</span></span></button>
					</div>
                </div>
            </li>
             <li class="item last">
					
						<a class="product-image" title="SuperFood Plus" href="https://www.herbdoc.com/superfood-plus-powder.html">
						<img style="float:left;" alt="SuperFood Plus" src="https://www.herbdoc.com/media/catalog/product/cache/1/small_image/210x/c96a280f94e22e3ee3823dd0a1a87606/s/u/superfood-powder_570_2.jpg" id="product-collection-image-572"></a><h2 class="product-name"><a title="SuperFood Plus" href="https://www.herbdoc.com/superfood-plus-powder.html">SuperFood Plus Powder</a></h2>
               
                <div class="product-info" style="min-height: 219px;">
                   
					<div class="size">14-ounce powder / 1-month supply</div>  <br>                  
					<div class="price-box">
						<span id="product-price-572" class="regular-price">                            
						<span class="price">ONLY  $32.00</span>
						</span>
						<p class="saving">
                        	<span class="price-label"><span style="color:#AA0803; font-weight:bold;">Save $8.00</span></span>
                        </p>

					</div>

					<div class="actions">
						<button onclick="setLocation('https://www.herbdoc.com/checkout/cart/add/uenc/aHR0cHM6Ly93d3cuaGVyYmRvYy5jb20vZm91bmRhdGlvbmFsL251dHJpdGlvbmFsLmh0bWw,/product/572/form_key/P9dURYwtdEBCizZJ/')" class="button btn-cart" title="Add to Cart" type="button"><span><span>ADD TO CART</span></span></button>
					</div>
                </div>
            </li>


		</ul>
    <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
</div>
</div>
</section>
 
 
 
 
 
 
<section class="section2 clearfix">
<div class="col-main">
	<div class="category-products">
            <ul style="margin-left: -3%; width: 106%;" class="products-grid products-grid--max-4-col first last odd">
						<li class="item last">
					
							<a class="product-image" title="SuperFood Plus" href="https://www.herbdoc.com/superfood-plus-tablets.html">
								<img style="float:left;" alt="SuperFood	 Plus" src="https://www.herbdoc.com/media/catalog/product/cache/1/small_image/210x/c96a280f94e22e3ee3823dd0a1a87606/s/u/superfood-tablets_570_2.jpg" id="product-collection-image-577"></a><h2 class="product-name"><a title="SuperFood Plus" href="https://www.herbdoc.com/superfood-plus-tablets.html">SuperFood Plus Tablets</a></h2>
							<div class="product-info" style="min-height: 219px;">
						
								<div class="size">390 tablets / 5-month supply</div>  <br>                  
								<div class="price-box">
									<span id="product-price-577" class="regular-price"><span class="price">ONLY  $138.00</span></span>
									<p class="saving">
									<span class="price-label"><span style="color:#AA0803; font-weight:bold;">Save $92.00</span></span>
									</p>
								</div>
								<div class="actions">
									<button onclick="setLocation('https://www.herbdoc.com/checkout/cart/add/uenc/aHR0cHM6Ly93d3cuaGVyYmRvYy5jb20vZm91bmRhdGlvbmFsL251dHJpdGlvbmFsLmh0bWw,/product/577/form_key/vb14hfvQS4kMWzoJ/')" class="button btn-cart" title="Add to Cart" type="button"><span><span>ORDER NOW</span></span></button>
								</div>
							</div>
						</li>             
	<li class="item last">
					
							<a class="product-image" title="SuperFood Plus" href="https://www.herbdoc.com/superfood-plus-tablets.html">
								<img style="float:left;" alt="SuperFood	 Plus" src="https://www.herbdoc.com/media/catalog/product/cache/1/small_image/210x/c96a280f94e22e3ee3823dd0a1a87606/s/u/superfood-tablets_570_2.jpg" id="product-collection-image-577"></a><h2 class="product-name"><a title="SuperFood Plus" href="https://www.herbdoc.com/superfood-plus-tablets.html">SuperFood Plus Tablets</a></h2>
							<div class="product-info" style="min-height: 219px;">
						
								<div class="size">390 tablets / 3-month supply</div><br>                    
								<div class="price-box">
									<span id="product-price-577" class="regular-price"><span class="price">ONLY  $92.00</span></span>
									<p class="saving">
									<span class="price-label"><span style="color:#AA0803; font-weight:bold;">Save $46.00</span></span>
									</p>
								</div>
								<div class="actions">
									<button onclick="setLocation('https://www.herbdoc.com/checkout/cart/add/uenc/aHR0cHM6Ly93d3cuaGVyYmRvYy5jb20vZm91bmRhdGlvbmFsL251dHJpdGlvbmFsLmh0bWw,/product/577/form_key/vb14hfvQS4kMWzoJ/')" class="button btn-cart" title="Add to Cart" type="button"><span><span>Add to Cart</span></span></button>
								</div>
							</div>
						</li> 
						<li class="item last">
					
							<a class="product-image" title="SuperFood Plus" href="https://www.herbdoc.com/superfood-plus-tablets.html">
								<img style="float:left;" alt="SuperFood	 Plus" src="https://www.herbdoc.com/media/catalog/product/cache/1/small_image/210x/c96a280f94e22e3ee3823dd0a1a87606/s/u/superfood-tablets_570_2.jpg" id="product-collection-image-577"></a><h2 class="product-name"><a title="SuperFood Plus" href="https://www.herbdoc.com/superfood-plus-tablets.html">SuperFood Plus</a></h2>
							<div class="product-info" style="min-height: 219px;">
						
								<div class="size">390 tablets / 1-month supply</div><br>                    
								<div class="price-box">
									<span id="product-price-577" class="regular-price"><span class="price">ONLY    $36.00</span></span>
									<p class="saving">
									<span class="price-label"><span style="color:#AA0803; font-weight:bold;">Save $10.00</span></span>
									</p>
								</div>
								<div class="actions">
									<button onclick="setLocation('https://www.herbdoc.com/checkout/cart/add/uenc/aHR0cHM6Ly93d3cuaGVyYmRvYy5jb20vZm91bmRhdGlvbmFsL251dHJpdGlvbmFsLmh0bWw,/product/577/form_key/vb14hfvQS4kMWzoJ/')" class="button btn-cart" title="Add to Cart" type="button"><span><span>Add to Cart</span></span></button>
								</div>
							</div>
						</li> 

		</ul>
    <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
</div>
</div>
</section>

 
 
 <div class="widget widget-static-block">
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('home_section2')->toHtml(); 
?> 
</div>


